//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.servicioGestorFileServer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWCFgestorFileServer", Namespace="http://tempuri.org/")]
    public partial class WCFgestorFileServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcesoGestorFileServerOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesoGetByteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFgestorFileServer() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_servicioGestorFileServer_WCFgestorFileServer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcesoGestorFileServerCompletedEventHandler ProcesoGestorFileServerCompleted;
        
        /// <remarks/>
        public event ProcesoGetByteCompletedEventHandler ProcesoGetByteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFgestorFileServer/ProcesoGestorFileServer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public getResultWSGFileServer ProcesoGestorFileServer([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] setDatosWSGFileServer datos) {
            object[] results = this.Invoke("ProcesoGestorFileServer", new object[] {
                        datos});
            return ((getResultWSGFileServer)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesoGestorFileServerAsync(setDatosWSGFileServer datos) {
            this.ProcesoGestorFileServerAsync(datos, null);
        }
        
        /// <remarks/>
        public void ProcesoGestorFileServerAsync(setDatosWSGFileServer datos, object userState) {
            if ((this.ProcesoGestorFileServerOperationCompleted == null)) {
                this.ProcesoGestorFileServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesoGestorFileServerOperationCompleted);
            }
            this.InvokeAsync("ProcesoGestorFileServer", new object[] {
                        datos}, this.ProcesoGestorFileServerOperationCompleted, userState);
        }
        
        private void OnProcesoGestorFileServerOperationCompleted(object arg) {
            if ((this.ProcesoGestorFileServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesoGestorFileServerCompleted(this, new ProcesoGestorFileServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFgestorFileServer/ProcesoGetByte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public setDatosWSGFileServer ProcesoGetByte([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] setDatosWSGFileServer datos) {
            object[] results = this.Invoke("ProcesoGetByte", new object[] {
                        datos});
            return ((setDatosWSGFileServer)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesoGetByteAsync(setDatosWSGFileServer datos) {
            this.ProcesoGetByteAsync(datos, null);
        }
        
        /// <remarks/>
        public void ProcesoGetByteAsync(setDatosWSGFileServer datos, object userState) {
            if ((this.ProcesoGetByteOperationCompleted == null)) {
                this.ProcesoGetByteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesoGetByteOperationCompleted);
            }
            this.InvokeAsync("ProcesoGetByte", new object[] {
                        datos}, this.ProcesoGetByteOperationCompleted, userState);
        }
        
        private void OnProcesoGetByteOperationCompleted(object arg) {
            if ((this.ProcesoGetByteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesoGetByteCompleted(this, new ProcesoGetByteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.ServicioW")]
    public partial class setDatosWSGFileServer : getResultWSGFileServer {
        
        private byte[] bOrigenArchivoField;
        
        private bool iFlagGrabaArchivoBDField;
        
        private bool iFlagGrabaArchivoBDFieldSpecified;
        
        private int iIdDocField;
        
        private bool iIdDocFieldSpecified;
        
        private int iIdSisField;
        
        private bool iIdSisFieldSpecified;
        
        private int iTipoArchivoField;
        
        private bool iTipoArchivoFieldSpecified;
        
        private long lIdSisField;
        
        private bool lIdSisFieldSpecified;
        
        private long lIdUsuarioField;
        
        private bool lIdUsuarioFieldSpecified;
        
        private long lSizeArchivoField;
        
        private bool lSizeArchivoFieldSpecified;
        
        private string sCodCmsField;
        
        private string sIpMaquinaField;
        
        private string sNombreArchivoField;
        
        private string sNombreArchivoAbrField;
        
        private string sPassRedField;
        
        private string sRutaArchivoField;
        
        private string sTipoAccionField;
        
        private string sUbiDestinoArchivoField;
        
        private string sUbiOrigenArchivoField;
        
        private string sUserRedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] bOrigenArchivo {
            get {
                return this.bOrigenArchivoField;
            }
            set {
                this.bOrigenArchivoField = value;
            }
        }
        
        /// <remarks/>
        public bool iFlagGrabaArchivoBD {
            get {
                return this.iFlagGrabaArchivoBDField;
            }
            set {
                this.iFlagGrabaArchivoBDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iFlagGrabaArchivoBDSpecified {
            get {
                return this.iFlagGrabaArchivoBDFieldSpecified;
            }
            set {
                this.iFlagGrabaArchivoBDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int iIdDoc {
            get {
                return this.iIdDocField;
            }
            set {
                this.iIdDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iIdDocSpecified {
            get {
                return this.iIdDocFieldSpecified;
            }
            set {
                this.iIdDocFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int iIdSis {
            get {
                return this.iIdSisField;
            }
            set {
                this.iIdSisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iIdSisSpecified {
            get {
                return this.iIdSisFieldSpecified;
            }
            set {
                this.iIdSisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int iTipoArchivo {
            get {
                return this.iTipoArchivoField;
            }
            set {
                this.iTipoArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iTipoArchivoSpecified {
            get {
                return this.iTipoArchivoFieldSpecified;
            }
            set {
                this.iTipoArchivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long lIdSis {
            get {
                return this.lIdSisField;
            }
            set {
                this.lIdSisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lIdSisSpecified {
            get {
                return this.lIdSisFieldSpecified;
            }
            set {
                this.lIdSisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long lIdUsuario {
            get {
                return this.lIdUsuarioField;
            }
            set {
                this.lIdUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lIdUsuarioSpecified {
            get {
                return this.lIdUsuarioFieldSpecified;
            }
            set {
                this.lIdUsuarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long lSizeArchivo {
            get {
                return this.lSizeArchivoField;
            }
            set {
                this.lSizeArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lSizeArchivoSpecified {
            get {
                return this.lSizeArchivoFieldSpecified;
            }
            set {
                this.lSizeArchivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sCodCms {
            get {
                return this.sCodCmsField;
            }
            set {
                this.sCodCmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sIpMaquina {
            get {
                return this.sIpMaquinaField;
            }
            set {
                this.sIpMaquinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sNombreArchivo {
            get {
                return this.sNombreArchivoField;
            }
            set {
                this.sNombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sNombreArchivoAbr {
            get {
                return this.sNombreArchivoAbrField;
            }
            set {
                this.sNombreArchivoAbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sPassRed {
            get {
                return this.sPassRedField;
            }
            set {
                this.sPassRedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sRutaArchivo {
            get {
                return this.sRutaArchivoField;
            }
            set {
                this.sRutaArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sTipoAccion {
            get {
                return this.sTipoAccionField;
            }
            set {
                this.sTipoAccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sUbiDestinoArchivo {
            get {
                return this.sUbiDestinoArchivoField;
            }
            set {
                this.sUbiDestinoArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sUbiOrigenArchivo {
            get {
                return this.sUbiOrigenArchivoField;
            }
            set {
                this.sUbiOrigenArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sUserRed {
            get {
                return this.sUserRedField;
            }
            set {
                this.sUserRedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(setDatosWSGFileServer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.ServicioW")]
    public partial class getResultWSGFileServer {
        
        private bool bSussessField;
        
        private bool bSussessFieldSpecified;
        
        private int iErrorField;
        
        private bool iErrorFieldSpecified;
        
        private long lIdDocCmsField;
        
        private bool lIdDocCmsFieldSpecified;
        
        private string sMensajeField;
        
        /// <remarks/>
        public bool bSussess {
            get {
                return this.bSussessField;
            }
            set {
                this.bSussessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bSussessSpecified {
            get {
                return this.bSussessFieldSpecified;
            }
            set {
                this.bSussessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int iError {
            get {
                return this.iErrorField;
            }
            set {
                this.iErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iErrorSpecified {
            get {
                return this.iErrorFieldSpecified;
            }
            set {
                this.iErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long lIdDocCms {
            get {
                return this.lIdDocCmsField;
            }
            set {
                this.lIdDocCmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lIdDocCmsSpecified {
            get {
                return this.lIdDocCmsFieldSpecified;
            }
            set {
                this.lIdDocCmsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                this.sMensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ProcesoGestorFileServerCompletedEventHandler(object sender, ProcesoGestorFileServerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesoGestorFileServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesoGestorFileServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getResultWSGFileServer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getResultWSGFileServer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ProcesoGetByteCompletedEventHandler(object sender, ProcesoGetByteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesoGetByteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesoGetByteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public setDatosWSGFileServer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((setDatosWSGFileServer)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591