//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.soap.ServicioUsuSisRolEntEstorg {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWCFSeguridadUsuSisRolEntEstorg", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resultado))]
    public partial class WCFSeguridadUsuSisRolEntEstorg : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listarUsuSisRolEntEstorgOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFSeguridadUsuSisRolEntEstorg() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_soap_ServicioUsuSisRolEntEstorg_WCFSeguridadUsuSisRolEntEstorg;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listarUsuSisRolEntEstorgCompletedEventHandler listarUsuSisRolEntEstorgCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSeguridadUsuSisRolEntEstorg/listarUsuSisRolEntEstorg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultadoUsuSisRolEstorg listarUsuSisRolEntEstorg([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DatosUsuSisRolEstorg datos) {
            object[] results = this.Invoke("listarUsuSisRolEntEstorg", new object[] {
                        datos});
            return ((ResultadoUsuSisRolEstorg)(results[0]));
        }
        
        /// <remarks/>
        public void listarUsuSisRolEntEstorgAsync(DatosUsuSisRolEstorg datos) {
            this.listarUsuSisRolEntEstorgAsync(datos, null);
        }
        
        /// <remarks/>
        public void listarUsuSisRolEntEstorgAsync(DatosUsuSisRolEstorg datos, object userState) {
            if ((this.listarUsuSisRolEntEstorgOperationCompleted == null)) {
                this.listarUsuSisRolEntEstorgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarUsuSisRolEntEstorgOperationCompleted);
            }
            this.InvokeAsync("listarUsuSisRolEntEstorg", new object[] {
                        datos}, this.listarUsuSisRolEntEstorgOperationCompleted, userState);
        }
        
        private void OnlistarUsuSisRolEntEstorgOperationCompleted(object arg) {
            if ((this.listarUsuSisRolEntEstorgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarUsuSisRolEntEstorgCompleted(this, new listarUsuSisRolEntEstorgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.Servici" +
        "oWeb.Models")]
    public partial class DatosUsuSisRolEstorg {
        
        private int idUsuField;
        
        private int idSisField;
        
        private string idRolField;
        
        private int idEntField;
        
        private int idSubField;
        
        private string idSubOfiField;
        
        private string datoField;
        
        private int flgEstField;
        
        private string oprField;
        
        /// <remarks/>
        public int IdUsu {
            get {
                return this.idUsuField;
            }
            set {
                this.idUsuField = value;
            }
        }
        
        /// <remarks/>
        public int IdSis {
            get {
                return this.idSisField;
            }
            set {
                this.idSisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
            }
        }
        
        /// <remarks/>
        public int IdEnt {
            get {
                return this.idEntField;
            }
            set {
                this.idEntField = value;
            }
        }
        
        /// <remarks/>
        public int IdSub {
            get {
                return this.idSubField;
            }
            set {
                this.idSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdSubOfi {
            get {
                return this.idSubOfiField;
            }
            set {
                this.idSubOfiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dato {
            get {
                return this.datoField;
            }
            set {
                this.datoField = value;
            }
        }
        
        /// <remarks/>
        public int FlgEst {
            get {
                return this.flgEstField;
            }
            set {
                this.flgEstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Opr {
            get {
                return this.oprField;
            }
            set {
                this.oprField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.Servici" +
        "oWeb.Models")]
    public partial class UsuSisRolEntEstorg {
        
        private int idUsuSisRolEntField;
        
        private bool idUsuSisRolEntFieldSpecified;
        
        private int idEntField;
        
        private bool idEntFieldSpecified;
        
        private string desEntField;
        
        private int idUsuField;
        
        private bool idUsuFieldSpecified;
        
        private string nomUsuField;
        
        private string nombresField;
        
        private string apePaterField;
        
        private string apeMaterField;
        
        private string correoField;
        
        private string codLogField;
        
        private int idSisField;
        
        private bool idSisFieldSpecified;
        
        private string desSisField;
        
        private string idRolField;
        
        private string desRolField;
        
        private string codEstField;
        
        private int idSubField;
        
        private bool idSubFieldSpecified;
        
        private string idSubOfiField;
        
        private string idOfiConcatField;
        
        private string desSubOfiField;
        
        private string abrSubOfiField;
        
        private string flgEstField;
        
        private string estadoField;
        
        /// <remarks/>
        public int IdUsuSisRolEnt {
            get {
                return this.idUsuSisRolEntField;
            }
            set {
                this.idUsuSisRolEntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUsuSisRolEntSpecified {
            get {
                return this.idUsuSisRolEntFieldSpecified;
            }
            set {
                this.idUsuSisRolEntFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdEnt {
            get {
                return this.idEntField;
            }
            set {
                this.idEntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdEntSpecified {
            get {
                return this.idEntFieldSpecified;
            }
            set {
                this.idEntFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesEnt {
            get {
                return this.desEntField;
            }
            set {
                this.desEntField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsu {
            get {
                return this.idUsuField;
            }
            set {
                this.idUsuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUsuSpecified {
            get {
                return this.idUsuFieldSpecified;
            }
            set {
                this.idUsuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NomUsu {
            get {
                return this.nomUsuField;
            }
            set {
                this.nomUsuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApePater {
            get {
                return this.apePaterField;
            }
            set {
                this.apePaterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApeMater {
            get {
                return this.apeMaterField;
            }
            set {
                this.apeMaterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodLog {
            get {
                return this.codLogField;
            }
            set {
                this.codLogField = value;
            }
        }
        
        /// <remarks/>
        public int IdSis {
            get {
                return this.idSisField;
            }
            set {
                this.idSisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSisSpecified {
            get {
                return this.idSisFieldSpecified;
            }
            set {
                this.idSisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesSis {
            get {
                return this.desSisField;
            }
            set {
                this.desSisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesRol {
            get {
                return this.desRolField;
            }
            set {
                this.desRolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodEst {
            get {
                return this.codEstField;
            }
            set {
                this.codEstField = value;
            }
        }
        
        /// <remarks/>
        public int IdSub {
            get {
                return this.idSubField;
            }
            set {
                this.idSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSubSpecified {
            get {
                return this.idSubFieldSpecified;
            }
            set {
                this.idSubFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdSubOfi {
            get {
                return this.idSubOfiField;
            }
            set {
                this.idSubOfiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdOfiConcat {
            get {
                return this.idOfiConcatField;
            }
            set {
                this.idOfiConcatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesSubOfi {
            get {
                return this.desSubOfiField;
            }
            set {
                this.desSubOfiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbrSubOfi {
            get {
                return this.abrSubOfiField;
            }
            set {
                this.abrSubOfiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FlgEst {
            get {
                return this.flgEstField;
            }
            set {
                this.flgEstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoUsuSisRolEstorg))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.Servici" +
        "oWeb.Models")]
    public partial class Resultado {
        
        private int idTipoField;
        
        private bool idTipoFieldSpecified;
        
        private string desErrorField;
        
        private string valorField;
        
        private string valor1Field;
        
        private string valor2Field;
        
        /// <remarks/>
        public int IdTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdTipoSpecified {
            get {
                return this.idTipoFieldSpecified;
            }
            set {
                this.idTipoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesError {
            get {
                return this.desErrorField;
            }
            set {
                this.desErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor1 {
            get {
                return this.valor1Field;
            }
            set {
                this.valor1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor2 {
            get {
                return this.valor2Field;
            }
            set {
                this.valor2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.Servici" +
        "oWeb.Models")]
    public partial class ResultadoUsuSisRolEstorg : Resultado {
        
        private UsuSisRolEntEstorg[] lstUsuSisRolEntEstorgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public UsuSisRolEntEstorg[] lstUsuSisRolEntEstorg {
            get {
                return this.lstUsuSisRolEntEstorgField;
            }
            set {
                this.lstUsuSisRolEntEstorgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void listarUsuSisRolEntEstorgCompletedEventHandler(object sender, listarUsuSisRolEntEstorgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarUsuSisRolEntEstorgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarUsuSisRolEntEstorgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoUsuSisRolEstorg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoUsuSisRolEstorg)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591