//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.soap.ServicioGeneralUtil.Correo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWCFGeneralesCorreo", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coHBase1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coHBase))]
    public partial class WCFGeneralesCorreo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback enviarCorreoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFGeneralesCorreo() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_soap_ServicioGeneralUtil_Correo_WCFGeneralesCorreo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event enviarCorreoCompletedEventHandler enviarCorreoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFGeneralesCorreo/enviarCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public coResultadoDB enviarCorreo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] enEmail oEnEmail) {
            object[] results = this.Invoke("enviarCorreo", new object[] {
                        oEnEmail});
            return ((coResultadoDB)(results[0]));
        }
        
        /// <remarks/>
        public void enviarCorreoAsync(enEmail oEnEmail) {
            this.enviarCorreoAsync(oEnEmail, null);
        }
        
        /// <remarks/>
        public void enviarCorreoAsync(enEmail oEnEmail, object userState) {
            if ((this.enviarCorreoOperationCompleted == null)) {
                this.enviarCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarCorreoOperationCompleted);
            }
            this.InvokeAsync("enviarCorreo", new object[] {
                        oEnEmail}, this.enviarCorreoOperationCompleted, userState);
        }
        
        private void OnenviarCorreoOperationCompleted(object arg) {
            if ((this.enviarCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarCorreoCompleted(this, new enviarCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.GeneralesUtil.EnG" +
        "eneralesUtil")]
    public partial class enEmail : coHBase {
        
        private string aSUNTOField;
        
        private string dES_SISField;
        
        private int fLAG_IMAGENField;
        
        private bool fLAG_IMAGENFieldSpecified;
        
        private int iD_SISField;
        
        private bool iD_SISFieldSpecified;
        
        private int iD_USUField;
        
        private bool iD_USUFieldSpecified;
        
        private string mAIL_DESTINOField;
        
        private string mAIL_ENVIAField;
        
        private string mENSAJEField;
        
        private string nOMBRE_DESTINOField;
        
        private string nOMBRE_ENVIAField;
        
        private string oFICINA_DESTINOField;
        
        private string oFICINA_ENVIAField;
        
        private int oPR_LINKField;
        
        private bool oPR_LINKFieldSpecified;
        
        private enLogError enLogErrorField;
        
        private string[] lstCorreoField;
        
        private string[] lstCorreoCCField;
        
        private string[] lstCorreoCCOField;
        
        private enDocumento[] lstEnDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ASUNTO {
            get {
                return this.aSUNTOField;
            }
            set {
                this.aSUNTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DES_SIS {
            get {
                return this.dES_SISField;
            }
            set {
                this.dES_SISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int FLAG_IMAGEN {
            get {
                return this.fLAG_IMAGENField;
            }
            set {
                this.fLAG_IMAGENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FLAG_IMAGENSpecified {
            get {
                return this.fLAG_IMAGENFieldSpecified;
            }
            set {
                this.fLAG_IMAGENFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ID_SIS {
            get {
                return this.iD_SISField;
            }
            set {
                this.iD_SISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SISSpecified {
            get {
                return this.iD_SISFieldSpecified;
            }
            set {
                this.iD_SISFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ID_USU {
            get {
                return this.iD_USUField;
            }
            set {
                this.iD_USUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_USUSpecified {
            get {
                return this.iD_USUFieldSpecified;
            }
            set {
                this.iD_USUFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string MAIL_DESTINO {
            get {
                return this.mAIL_DESTINOField;
            }
            set {
                this.mAIL_DESTINOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string MAIL_ENVIA {
            get {
                return this.mAIL_ENVIAField;
            }
            set {
                this.mAIL_ENVIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string MENSAJE {
            get {
                return this.mENSAJEField;
            }
            set {
                this.mENSAJEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string NOMBRE_DESTINO {
            get {
                return this.nOMBRE_DESTINOField;
            }
            set {
                this.nOMBRE_DESTINOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string NOMBRE_ENVIA {
            get {
                return this.nOMBRE_ENVIAField;
            }
            set {
                this.nOMBRE_ENVIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string OFICINA_DESTINO {
            get {
                return this.oFICINA_DESTINOField;
            }
            set {
                this.oFICINA_DESTINOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string OFICINA_ENVIA {
            get {
                return this.oFICINA_ENVIAField;
            }
            set {
                this.oFICINA_ENVIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int OPR_LINK {
            get {
                return this.oPR_LINKField;
            }
            set {
                this.oPR_LINKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OPR_LINKSpecified {
            get {
                return this.oPR_LINKFieldSpecified;
            }
            set {
                this.oPR_LINKFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public enLogError enLogError {
            get {
                return this.enLogErrorField;
            }
            set {
                this.enLogErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] lstCorreo {
            get {
                return this.lstCorreoField;
            }
            set {
                this.lstCorreoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] lstCorreoCC {
            get {
                return this.lstCorreoCCField;
            }
            set {
                this.lstCorreoCCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] lstCorreoCCO {
            get {
                return this.lstCorreoCCOField;
            }
            set {
                this.lstCorreoCCOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=17)]
        public enDocumento[] lstEnDocumento {
            get {
                return this.lstEnDocumentoField;
            }
            set {
                this.lstEnDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.EnSegur" +
        "idad")]
    public partial class enLogError : coHBase1 {
        
        private string cOD_FUENTEField;
        
        private string dES_ERRORField;
        
        private string dES_PAGINAOBJETOField;
        
        private System.DateTime fEC_CREAField;
        
        private bool fEC_CREAFieldSpecified;
        
        private int iD_LOGERRORField;
        
        private bool iD_LOGERRORFieldSpecified;
        
        private int iD_SISField;
        
        private bool iD_SISFieldSpecified;
        
        private string iP_CREAField;
        
        private int uSU_CREAField;
        
        private bool uSU_CREAFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COD_FUENTE {
            get {
                return this.cOD_FUENTEField;
            }
            set {
                this.cOD_FUENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DES_ERROR {
            get {
                return this.dES_ERRORField;
            }
            set {
                this.dES_ERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DES_PAGINAOBJETO {
            get {
                return this.dES_PAGINAOBJETOField;
            }
            set {
                this.dES_PAGINAOBJETOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FEC_CREA {
            get {
                return this.fEC_CREAField;
            }
            set {
                this.fEC_CREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEC_CREASpecified {
            get {
                return this.fEC_CREAFieldSpecified;
            }
            set {
                this.fEC_CREAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ID_LOGERROR {
            get {
                return this.iD_LOGERRORField;
            }
            set {
                this.iD_LOGERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_LOGERRORSpecified {
            get {
                return this.iD_LOGERRORFieldSpecified;
            }
            set {
                this.iD_LOGERRORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ID_SIS {
            get {
                return this.iD_SISField;
            }
            set {
                this.iD_SISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SISSpecified {
            get {
                return this.iD_SISFieldSpecified;
            }
            set {
                this.iD_SISFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IP_CREA {
            get {
                return this.iP_CREAField;
            }
            set {
                this.iP_CREAField = value;
            }
        }
        
        /// <remarks/>
        public int USU_CREA {
            get {
                return this.uSU_CREAField;
            }
            set {
                this.uSU_CREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USU_CREASpecified {
            get {
                return this.uSU_CREAFieldSpecified;
            }
            set {
                this.uSU_CREAFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enLogError))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="coHBase", Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.CoSegur" +
        "idad")]
    public partial class coHBase1 {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enTipoDocu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enDocumento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enEmail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coResultadoDB))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.GeneralesUtil.CoG" +
        "eneralesUtil")]
    public partial class coHBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enDocumento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.GeneralesUtil.EnG" +
        "eneralesUtil")]
    public partial class enTipoDocu : coHBase {
        
        private string aBR_EXTENSIONField;
        
        private string dES_EXTENSIONField;
        
        private string dES_RUTAField;
        
        private System.DateTime fEC_CREAField;
        
        private bool fEC_CREAFieldSpecified;
        
        private string fLG_ESTField;
        
        private int iD_TIPOField;
        
        private bool iD_TIPOFieldSpecified;
        
        private string oPRField;
        
        private int uSU_CREAField;
        
        private bool uSU_CREAFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ABR_EXTENSION {
            get {
                return this.aBR_EXTENSIONField;
            }
            set {
                this.aBR_EXTENSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DES_EXTENSION {
            get {
                return this.dES_EXTENSIONField;
            }
            set {
                this.dES_EXTENSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string DES_RUTA {
            get {
                return this.dES_RUTAField;
            }
            set {
                this.dES_RUTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FEC_CREA {
            get {
                return this.fEC_CREAField;
            }
            set {
                this.fEC_CREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEC_CREASpecified {
            get {
                return this.fEC_CREAFieldSpecified;
            }
            set {
                this.fEC_CREAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string FLG_EST {
            get {
                return this.fLG_ESTField;
            }
            set {
                this.fLG_ESTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ID_TIPO {
            get {
                return this.iD_TIPOField;
            }
            set {
                this.iD_TIPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_TIPOSpecified {
            get {
                return this.iD_TIPOFieldSpecified;
            }
            set {
                this.iD_TIPOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string OPR {
            get {
                return this.oPRField;
            }
            set {
                this.oPRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int USU_CREA {
            get {
                return this.uSU_CREAField;
            }
            set {
                this.uSU_CREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USU_CREASpecified {
            get {
                return this.uSU_CREAFieldSpecified;
            }
            set {
                this.uSU_CREAFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.GeneralesUtil.EnG" +
        "eneralesUtil")]
    public partial class enDocumento : enTipoDocu {
        
        private byte[] aRCHIVOField;
        
        private string dES_NOMField;
        
        private System.DateTime fEC_CREA1Field;
        
        private bool fEC_CREA1FieldSpecified;
        
        private System.DateTime fEC_MODIField;
        
        private bool fEC_MODIFieldSpecified;
        
        private int iD_DOCField;
        
        private bool iD_DOCFieldSpecified;
        
        private int iD_FORMField;
        
        private bool iD_FORMFieldSpecified;
        
        private int iD_SISField;
        
        private bool iD_SISFieldSpecified;
        
        private int nUM_SIZEARCHIVOField;
        
        private bool nUM_SIZEARCHIVOFieldSpecified;
        
        private string tEXTOField;
        
        private int uSU_CREA1Field;
        
        private bool uSU_CREA1FieldSpecified;
        
        private int uSU_MODIField;
        
        private bool uSU_MODIFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] ARCHIVO {
            get {
                return this.aRCHIVOField;
            }
            set {
                this.aRCHIVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DES_NOM {
            get {
                return this.dES_NOMField;
            }
            set {
                this.dES_NOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FEC_CREA", Order=2)]
        public System.DateTime FEC_CREA1 {
            get {
                return this.fEC_CREA1Field;
            }
            set {
                this.fEC_CREA1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEC_CREA1Specified {
            get {
                return this.fEC_CREA1FieldSpecified;
            }
            set {
                this.fEC_CREA1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FEC_MODI {
            get {
                return this.fEC_MODIField;
            }
            set {
                this.fEC_MODIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEC_MODISpecified {
            get {
                return this.fEC_MODIFieldSpecified;
            }
            set {
                this.fEC_MODIFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ID_DOC {
            get {
                return this.iD_DOCField;
            }
            set {
                this.iD_DOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_DOCSpecified {
            get {
                return this.iD_DOCFieldSpecified;
            }
            set {
                this.iD_DOCFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ID_FORM {
            get {
                return this.iD_FORMField;
            }
            set {
                this.iD_FORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_FORMSpecified {
            get {
                return this.iD_FORMFieldSpecified;
            }
            set {
                this.iD_FORMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ID_SIS {
            get {
                return this.iD_SISField;
            }
            set {
                this.iD_SISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SISSpecified {
            get {
                return this.iD_SISFieldSpecified;
            }
            set {
                this.iD_SISFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int NUM_SIZEARCHIVO {
            get {
                return this.nUM_SIZEARCHIVOField;
            }
            set {
                this.nUM_SIZEARCHIVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUM_SIZEARCHIVOSpecified {
            get {
                return this.nUM_SIZEARCHIVOFieldSpecified;
            }
            set {
                this.nUM_SIZEARCHIVOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string TEXTO {
            get {
                return this.tEXTOField;
            }
            set {
                this.tEXTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USU_CREA", Order=9)]
        public int USU_CREA1 {
            get {
                return this.uSU_CREA1Field;
            }
            set {
                this.uSU_CREA1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USU_CREA1Specified {
            get {
                return this.uSU_CREA1FieldSpecified;
            }
            set {
                this.uSU_CREA1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int USU_MODI {
            get {
                return this.uSU_MODIField;
            }
            set {
                this.uSU_MODIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USU_MODISpecified {
            get {
                return this.uSU_MODIFieldSpecified;
            }
            set {
                this.uSU_MODIFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.GeneralesUtil.CoG" +
        "eneralesUtil")]
    public partial class coResultadoDB : coHBase {
        
        private string dES_ERRORField;
        
        private string iD_ERRORField;
        
        private int iD_TIPOField;
        
        private bool iD_TIPOFieldSpecified;
        
        private int vALORField;
        
        private bool vALORFieldSpecified;
        
        private int vALOR1Field;
        
        private bool vALOR1FieldSpecified;
        
        private int vALOR10Field;
        
        private bool vALOR10FieldSpecified;
        
        private int vALOR2Field;
        
        private bool vALOR2FieldSpecified;
        
        private int vALOR3Field;
        
        private bool vALOR3FieldSpecified;
        
        private int vALOR4Field;
        
        private bool vALOR4FieldSpecified;
        
        private int vALOR5Field;
        
        private bool vALOR5FieldSpecified;
        
        private int vALOR6Field;
        
        private bool vALOR6FieldSpecified;
        
        private int vALOR7Field;
        
        private bool vALOR7FieldSpecified;
        
        private int vALOR8Field;
        
        private bool vALOR8FieldSpecified;
        
        private int vALOR9Field;
        
        private bool vALOR9FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string DES_ERROR {
            get {
                return this.dES_ERRORField;
            }
            set {
                this.dES_ERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ID_ERROR {
            get {
                return this.iD_ERRORField;
            }
            set {
                this.iD_ERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ID_TIPO {
            get {
                return this.iD_TIPOField;
            }
            set {
                this.iD_TIPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_TIPOSpecified {
            get {
                return this.iD_TIPOFieldSpecified;
            }
            set {
                this.iD_TIPOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int VALOR {
            get {
                return this.vALORField;
            }
            set {
                this.vALORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALORSpecified {
            get {
                return this.vALORFieldSpecified;
            }
            set {
                this.vALORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int VALOR1 {
            get {
                return this.vALOR1Field;
            }
            set {
                this.vALOR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR1Specified {
            get {
                return this.vALOR1FieldSpecified;
            }
            set {
                this.vALOR1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int VALOR10 {
            get {
                return this.vALOR10Field;
            }
            set {
                this.vALOR10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR10Specified {
            get {
                return this.vALOR10FieldSpecified;
            }
            set {
                this.vALOR10FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int VALOR2 {
            get {
                return this.vALOR2Field;
            }
            set {
                this.vALOR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR2Specified {
            get {
                return this.vALOR2FieldSpecified;
            }
            set {
                this.vALOR2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int VALOR3 {
            get {
                return this.vALOR3Field;
            }
            set {
                this.vALOR3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR3Specified {
            get {
                return this.vALOR3FieldSpecified;
            }
            set {
                this.vALOR3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int VALOR4 {
            get {
                return this.vALOR4Field;
            }
            set {
                this.vALOR4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR4Specified {
            get {
                return this.vALOR4FieldSpecified;
            }
            set {
                this.vALOR4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int VALOR5 {
            get {
                return this.vALOR5Field;
            }
            set {
                this.vALOR5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR5Specified {
            get {
                return this.vALOR5FieldSpecified;
            }
            set {
                this.vALOR5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int VALOR6 {
            get {
                return this.vALOR6Field;
            }
            set {
                this.vALOR6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR6Specified {
            get {
                return this.vALOR6FieldSpecified;
            }
            set {
                this.vALOR6FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int VALOR7 {
            get {
                return this.vALOR7Field;
            }
            set {
                this.vALOR7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR7Specified {
            get {
                return this.vALOR7FieldSpecified;
            }
            set {
                this.vALOR7FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int VALOR8 {
            get {
                return this.vALOR8Field;
            }
            set {
                this.vALOR8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR8Specified {
            get {
                return this.vALOR8FieldSpecified;
            }
            set {
                this.vALOR8FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int VALOR9 {
            get {
                return this.vALOR9Field;
            }
            set {
                this.vALOR9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR9Specified {
            get {
                return this.vALOR9FieldSpecified;
            }
            set {
                this.vALOR9FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void enviarCorreoCompletedEventHandler(object sender, enviarCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public coResultadoDB Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((coResultadoDB)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591