//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.servicioSeguridad.WCFSeguridadEncripDesencrip {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWCFSeguridadEncripDesencrip", Namespace="http://tempuri.org/")]
    public partial class WCFSeguridadEncripDesencrip : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback encriptarAESOperationCompleted;
        
        private System.Threading.SendOrPostCallback desencriptarAESOperationCompleted;
        
        private System.Threading.SendOrPostCallback traeLlaveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFSeguridadEncripDesencrip() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_servicioSeguridad_WCFSeguridadEncripDesencrip_WCFSeguridadEncripDesencrip;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event encriptarAESCompletedEventHandler encriptarAESCompleted;
        
        /// <remarks/>
        public event desencriptarAESCompletedEventHandler desencriptarAESCompleted;
        
        /// <remarks/>
        public event traeLlaveCompletedEventHandler traeLlaveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSeguridadEncripDesencrip/encriptarAES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string encriptarAES([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string plainText, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave) {
            object[] results = this.Invoke("encriptarAES", new object[] {
                        plainText,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void encriptarAESAsync(string plainText, string clave) {
            this.encriptarAESAsync(plainText, clave, null);
        }
        
        /// <remarks/>
        public void encriptarAESAsync(string plainText, string clave, object userState) {
            if ((this.encriptarAESOperationCompleted == null)) {
                this.encriptarAESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnencriptarAESOperationCompleted);
            }
            this.InvokeAsync("encriptarAES", new object[] {
                        plainText,
                        clave}, this.encriptarAESOperationCompleted, userState);
        }
        
        private void OnencriptarAESOperationCompleted(object arg) {
            if ((this.encriptarAESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.encriptarAESCompleted(this, new encriptarAESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSeguridadEncripDesencrip/desencriptarAES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desencriptarAES([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string encryptText, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clave) {
            object[] results = this.Invoke("desencriptarAES", new object[] {
                        encryptText,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void desencriptarAESAsync(string encryptText, string clave) {
            this.desencriptarAESAsync(encryptText, clave, null);
        }
        
        /// <remarks/>
        public void desencriptarAESAsync(string encryptText, string clave, object userState) {
            if ((this.desencriptarAESOperationCompleted == null)) {
                this.desencriptarAESOperationCompleted = new System.Threading.SendOrPostCallback(this.OndesencriptarAESOperationCompleted);
            }
            this.InvokeAsync("desencriptarAES", new object[] {
                        encryptText,
                        clave}, this.desencriptarAESOperationCompleted, userState);
        }
        
        private void OndesencriptarAESOperationCompleted(object arg) {
            if ((this.desencriptarAESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.desencriptarAESCompleted(this, new desencriptarAESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSeguridadEncripDesencrip/traeLlave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string traeLlave() {
            object[] results = this.Invoke("traeLlave", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void traeLlaveAsync() {
            this.traeLlaveAsync(null);
        }
        
        /// <remarks/>
        public void traeLlaveAsync(object userState) {
            if ((this.traeLlaveOperationCompleted == null)) {
                this.traeLlaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OntraeLlaveOperationCompleted);
            }
            this.InvokeAsync("traeLlave", new object[0], this.traeLlaveOperationCompleted, userState);
        }
        
        private void OntraeLlaveOperationCompleted(object arg) {
            if ((this.traeLlaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.traeLlaveCompleted(this, new traeLlaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void encriptarAESCompletedEventHandler(object sender, encriptarAESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class encriptarAESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal encriptarAESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void desencriptarAESCompletedEventHandler(object sender, desencriptarAESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class desencriptarAESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal desencriptarAESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void traeLlaveCompletedEventHandler(object sender, traeLlaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traeLlaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal traeLlaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591