//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.soap.ServicioSeguridad.SeguridadSistema {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWCFSeguridadSistema", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coHBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enTipoAcceso))]
    public partial class WCFSeguridadSistema : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listarAccesosPorDiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarAccesoOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarAccesoUltOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFSeguridadSistema() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_soap_ServicioSeguridad_SeguridadSistema_WCFSeguridadSistema;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listarAccesosPorDiaCompletedEventHandler listarAccesosPorDiaCompleted;
        
        /// <remarks/>
        public event enviarAccesoCompletedEventHandler enviarAccesoCompleted;
        
        /// <remarks/>
        public event enviarAccesoUltCompletedEventHandler enviarAccesoUltCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSeguridadSistema/listarAccesosPorDia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.EnSegur" +
            "idad")]
        public enAcceso[] listarAccesosPorDia([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] enAcceso objEnAcceso) {
            object[] results = this.Invoke("listarAccesosPorDia", new object[] {
                        objEnAcceso});
            return ((enAcceso[])(results[0]));
        }
        
        /// <remarks/>
        public void listarAccesosPorDiaAsync(enAcceso objEnAcceso) {
            this.listarAccesosPorDiaAsync(objEnAcceso, null);
        }
        
        /// <remarks/>
        public void listarAccesosPorDiaAsync(enAcceso objEnAcceso, object userState) {
            if ((this.listarAccesosPorDiaOperationCompleted == null)) {
                this.listarAccesosPorDiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarAccesosPorDiaOperationCompleted);
            }
            this.InvokeAsync("listarAccesosPorDia", new object[] {
                        objEnAcceso}, this.listarAccesosPorDiaOperationCompleted, userState);
        }
        
        private void OnlistarAccesosPorDiaOperationCompleted(object arg) {
            if ((this.listarAccesosPorDiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarAccesosPorDiaCompleted(this, new listarAccesosPorDiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSeguridadSistema/enviarAcceso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public coResultadoDB enviarAcceso([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] enAcceso objEnAcceso) {
            object[] results = this.Invoke("enviarAcceso", new object[] {
                        objEnAcceso});
            return ((coResultadoDB)(results[0]));
        }
        
        /// <remarks/>
        public void enviarAccesoAsync(enAcceso objEnAcceso) {
            this.enviarAccesoAsync(objEnAcceso, null);
        }
        
        /// <remarks/>
        public void enviarAccesoAsync(enAcceso objEnAcceso, object userState) {
            if ((this.enviarAccesoOperationCompleted == null)) {
                this.enviarAccesoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarAccesoOperationCompleted);
            }
            this.InvokeAsync("enviarAcceso", new object[] {
                        objEnAcceso}, this.enviarAccesoOperationCompleted, userState);
        }
        
        private void OnenviarAccesoOperationCompleted(object arg) {
            if ((this.enviarAccesoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarAccesoCompleted(this, new enviarAccesoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSeguridadSistema/enviarAccesoUlt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public coResultadoDB enviarAccesoUlt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] enAcceso objEnAcceso) {
            object[] results = this.Invoke("enviarAccesoUlt", new object[] {
                        objEnAcceso});
            return ((coResultadoDB)(results[0]));
        }
        
        /// <remarks/>
        public void enviarAccesoUltAsync(enAcceso objEnAcceso) {
            this.enviarAccesoUltAsync(objEnAcceso, null);
        }
        
        /// <remarks/>
        public void enviarAccesoUltAsync(enAcceso objEnAcceso, object userState) {
            if ((this.enviarAccesoUltOperationCompleted == null)) {
                this.enviarAccesoUltOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarAccesoUltOperationCompleted);
            }
            this.InvokeAsync("enviarAccesoUlt", new object[] {
                        objEnAcceso}, this.enviarAccesoUltOperationCompleted, userState);
        }
        
        private void OnenviarAccesoUltOperationCompleted(object arg) {
            if ((this.enviarAccesoUltCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarAccesoUltCompleted(this, new enviarAccesoUltCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.EnSegur" +
        "idad")]
    public partial class enAcceso : enTipoAcceso {
        
        private int cANTIDADField;
        
        private bool cANTIDADFieldSpecified;
        
        private string cOD_FUENTEField;
        
        private string dES_OBSField;
        
        private string dES_SISField;
        
        private string dES_URLField;
        
        private System.DateTime fEC_ACCESOField;
        
        private bool fEC_ACCESOFieldSpecified;
        
        private string fEC_INIField;
        
        private int fLG_MOVILField;
        
        private bool fLG_MOVILFieldSpecified;
        
        private int iD_ACCESOField;
        
        private bool iD_ACCESOFieldSpecified;
        
        private int iD_PERSONAField;
        
        private bool iD_PERSONAFieldSpecified;
        
        private int iD_SISField;
        
        private bool iD_SISFieldSpecified;
        
        private string iP_ACCESOField;
        
        private int oRDENField;
        
        private bool oRDENFieldSpecified;
        
        private enGeoPlugin enGeoPluginField;
        
        /// <remarks/>
        public int CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CANTIDADSpecified {
            get {
                return this.cANTIDADFieldSpecified;
            }
            set {
                this.cANTIDADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COD_FUENTE {
            get {
                return this.cOD_FUENTEField;
            }
            set {
                this.cOD_FUENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DES_OBS {
            get {
                return this.dES_OBSField;
            }
            set {
                this.dES_OBSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DES_SIS {
            get {
                return this.dES_SISField;
            }
            set {
                this.dES_SISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DES_URL {
            get {
                return this.dES_URLField;
            }
            set {
                this.dES_URLField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FEC_ACCESO {
            get {
                return this.fEC_ACCESOField;
            }
            set {
                this.fEC_ACCESOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEC_ACCESOSpecified {
            get {
                return this.fEC_ACCESOFieldSpecified;
            }
            set {
                this.fEC_ACCESOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FEC_INI {
            get {
                return this.fEC_INIField;
            }
            set {
                this.fEC_INIField = value;
            }
        }
        
        /// <remarks/>
        public int FLG_MOVIL {
            get {
                return this.fLG_MOVILField;
            }
            set {
                this.fLG_MOVILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FLG_MOVILSpecified {
            get {
                return this.fLG_MOVILFieldSpecified;
            }
            set {
                this.fLG_MOVILFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ID_ACCESO {
            get {
                return this.iD_ACCESOField;
            }
            set {
                this.iD_ACCESOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_ACCESOSpecified {
            get {
                return this.iD_ACCESOFieldSpecified;
            }
            set {
                this.iD_ACCESOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ID_PERSONA {
            get {
                return this.iD_PERSONAField;
            }
            set {
                this.iD_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_PERSONASpecified {
            get {
                return this.iD_PERSONAFieldSpecified;
            }
            set {
                this.iD_PERSONAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ID_SIS {
            get {
                return this.iD_SISField;
            }
            set {
                this.iD_SISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SISSpecified {
            get {
                return this.iD_SISFieldSpecified;
            }
            set {
                this.iD_SISFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IP_ACCESO {
            get {
                return this.iP_ACCESOField;
            }
            set {
                this.iP_ACCESOField = value;
            }
        }
        
        /// <remarks/>
        public int ORDEN {
            get {
                return this.oRDENField;
            }
            set {
                this.oRDENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORDENSpecified {
            get {
                return this.oRDENFieldSpecified;
            }
            set {
                this.oRDENFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public enGeoPlugin enGeoPlugin {
            get {
                return this.enGeoPluginField;
            }
            set {
                this.enGeoPluginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.EnSegur" +
        "idad")]
    public partial class enGeoPlugin : coHBase {
        
        private string gEOPLUGIN_AREACODEField;
        
        private string gEOPLUGIN_CITYField;
        
        private string gEOPLUGIN_CONTINENTCODEField;
        
        private string gEOPLUGIN_COUNTRYCODEField;
        
        private string gEOPLUGIN_COUNTRYNAMEField;
        
        private string gEOPLUGIN_CURRENCYCODEField;
        
        private string gEOPLUGIN_DMACODEField;
        
        private decimal gEOPLUGIN_LATITUDEField;
        
        private bool gEOPLUGIN_LATITUDEFieldSpecified;
        
        private decimal gEOPLUGIN_LONGITUDEField;
        
        private bool gEOPLUGIN_LONGITUDEFieldSpecified;
        
        private string gEOPLUGIN_REGIONField;
        
        private string gEOPLUGIN_REGIONCODEField;
        
        private string gEOPLUGIN_REGIONNAMEField;
        
        private string gEOPLUGIN_REQUESTField;
        
        private string gEOPLUGIN_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_AREACODE {
            get {
                return this.gEOPLUGIN_AREACODEField;
            }
            set {
                this.gEOPLUGIN_AREACODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_CITY {
            get {
                return this.gEOPLUGIN_CITYField;
            }
            set {
                this.gEOPLUGIN_CITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_CONTINENTCODE {
            get {
                return this.gEOPLUGIN_CONTINENTCODEField;
            }
            set {
                this.gEOPLUGIN_CONTINENTCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_COUNTRYCODE {
            get {
                return this.gEOPLUGIN_COUNTRYCODEField;
            }
            set {
                this.gEOPLUGIN_COUNTRYCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_COUNTRYNAME {
            get {
                return this.gEOPLUGIN_COUNTRYNAMEField;
            }
            set {
                this.gEOPLUGIN_COUNTRYNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_CURRENCYCODE {
            get {
                return this.gEOPLUGIN_CURRENCYCODEField;
            }
            set {
                this.gEOPLUGIN_CURRENCYCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_DMACODE {
            get {
                return this.gEOPLUGIN_DMACODEField;
            }
            set {
                this.gEOPLUGIN_DMACODEField = value;
            }
        }
        
        /// <remarks/>
        public decimal GEOPLUGIN_LATITUDE {
            get {
                return this.gEOPLUGIN_LATITUDEField;
            }
            set {
                this.gEOPLUGIN_LATITUDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GEOPLUGIN_LATITUDESpecified {
            get {
                return this.gEOPLUGIN_LATITUDEFieldSpecified;
            }
            set {
                this.gEOPLUGIN_LATITUDEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal GEOPLUGIN_LONGITUDE {
            get {
                return this.gEOPLUGIN_LONGITUDEField;
            }
            set {
                this.gEOPLUGIN_LONGITUDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GEOPLUGIN_LONGITUDESpecified {
            get {
                return this.gEOPLUGIN_LONGITUDEFieldSpecified;
            }
            set {
                this.gEOPLUGIN_LONGITUDEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_REGION {
            get {
                return this.gEOPLUGIN_REGIONField;
            }
            set {
                this.gEOPLUGIN_REGIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_REGIONCODE {
            get {
                return this.gEOPLUGIN_REGIONCODEField;
            }
            set {
                this.gEOPLUGIN_REGIONCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_REGIONNAME {
            get {
                return this.gEOPLUGIN_REGIONNAMEField;
            }
            set {
                this.gEOPLUGIN_REGIONNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_REQUEST {
            get {
                return this.gEOPLUGIN_REQUESTField;
            }
            set {
                this.gEOPLUGIN_REQUESTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GEOPLUGIN_STATUS {
            get {
                return this.gEOPLUGIN_STATUSField;
            }
            set {
                this.gEOPLUGIN_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coResultadoDB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enGeoPlugin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.CoSegur" +
        "idad")]
    public partial class coHBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enAcceso))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.EnSegur" +
        "idad")]
    public partial class enTipoAcceso {
        
        private string dES_TIPOACCESOField;
        
        private System.DateTime fEC_CREAField;
        
        private bool fEC_CREAFieldSpecified;
        
        private System.DateTime fEC_MODIField;
        
        private bool fEC_MODIFieldSpecified;
        
        private int iD_TIPOACCESOField;
        
        private bool iD_TIPOACCESOFieldSpecified;
        
        private string oPRField;
        
        private int uSU_CREAField;
        
        private bool uSU_CREAFieldSpecified;
        
        private int uSU_MODIField;
        
        private bool uSU_MODIFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DES_TIPOACCESO {
            get {
                return this.dES_TIPOACCESOField;
            }
            set {
                this.dES_TIPOACCESOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FEC_CREA {
            get {
                return this.fEC_CREAField;
            }
            set {
                this.fEC_CREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEC_CREASpecified {
            get {
                return this.fEC_CREAFieldSpecified;
            }
            set {
                this.fEC_CREAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FEC_MODI {
            get {
                return this.fEC_MODIField;
            }
            set {
                this.fEC_MODIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FEC_MODISpecified {
            get {
                return this.fEC_MODIFieldSpecified;
            }
            set {
                this.fEC_MODIFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ID_TIPOACCESO {
            get {
                return this.iD_TIPOACCESOField;
            }
            set {
                this.iD_TIPOACCESOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_TIPOACCESOSpecified {
            get {
                return this.iD_TIPOACCESOFieldSpecified;
            }
            set {
                this.iD_TIPOACCESOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OPR {
            get {
                return this.oPRField;
            }
            set {
                this.oPRField = value;
            }
        }
        
        /// <remarks/>
        public int USU_CREA {
            get {
                return this.uSU_CREAField;
            }
            set {
                this.uSU_CREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USU_CREASpecified {
            get {
                return this.uSU_CREAFieldSpecified;
            }
            set {
                this.uSU_CREAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int USU_MODI {
            get {
                return this.uSU_MODIField;
            }
            set {
                this.uSU_MODIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USU_MODISpecified {
            get {
                return this.uSU_MODIFieldSpecified;
            }
            set {
                this.uSU_MODIFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.Administracion.Seguridad.CoSegur" +
        "idad")]
    public partial class coResultadoDB : coHBase {
        
        private string dES_ERRORField;
        
        private string iD_ERRORField;
        
        private int iD_TIPOField;
        
        private bool iD_TIPOFieldSpecified;
        
        private int vALORField;
        
        private bool vALORFieldSpecified;
        
        private int vALOR1Field;
        
        private bool vALOR1FieldSpecified;
        
        private int vALOR10Field;
        
        private bool vALOR10FieldSpecified;
        
        private int vALOR2Field;
        
        private bool vALOR2FieldSpecified;
        
        private int vALOR3Field;
        
        private bool vALOR3FieldSpecified;
        
        private int vALOR4Field;
        
        private bool vALOR4FieldSpecified;
        
        private int vALOR5Field;
        
        private bool vALOR5FieldSpecified;
        
        private int vALOR6Field;
        
        private bool vALOR6FieldSpecified;
        
        private int vALOR7Field;
        
        private bool vALOR7FieldSpecified;
        
        private int vALOR8Field;
        
        private bool vALOR8FieldSpecified;
        
        private int vALOR9Field;
        
        private bool vALOR9FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DES_ERROR {
            get {
                return this.dES_ERRORField;
            }
            set {
                this.dES_ERRORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ID_ERROR {
            get {
                return this.iD_ERRORField;
            }
            set {
                this.iD_ERRORField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TIPO {
            get {
                return this.iD_TIPOField;
            }
            set {
                this.iD_TIPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_TIPOSpecified {
            get {
                return this.iD_TIPOFieldSpecified;
            }
            set {
                this.iD_TIPOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR {
            get {
                return this.vALORField;
            }
            set {
                this.vALORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALORSpecified {
            get {
                return this.vALORFieldSpecified;
            }
            set {
                this.vALORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR1 {
            get {
                return this.vALOR1Field;
            }
            set {
                this.vALOR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR1Specified {
            get {
                return this.vALOR1FieldSpecified;
            }
            set {
                this.vALOR1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR10 {
            get {
                return this.vALOR10Field;
            }
            set {
                this.vALOR10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR10Specified {
            get {
                return this.vALOR10FieldSpecified;
            }
            set {
                this.vALOR10FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR2 {
            get {
                return this.vALOR2Field;
            }
            set {
                this.vALOR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR2Specified {
            get {
                return this.vALOR2FieldSpecified;
            }
            set {
                this.vALOR2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR3 {
            get {
                return this.vALOR3Field;
            }
            set {
                this.vALOR3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR3Specified {
            get {
                return this.vALOR3FieldSpecified;
            }
            set {
                this.vALOR3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR4 {
            get {
                return this.vALOR4Field;
            }
            set {
                this.vALOR4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR4Specified {
            get {
                return this.vALOR4FieldSpecified;
            }
            set {
                this.vALOR4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR5 {
            get {
                return this.vALOR5Field;
            }
            set {
                this.vALOR5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR5Specified {
            get {
                return this.vALOR5FieldSpecified;
            }
            set {
                this.vALOR5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR6 {
            get {
                return this.vALOR6Field;
            }
            set {
                this.vALOR6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR6Specified {
            get {
                return this.vALOR6FieldSpecified;
            }
            set {
                this.vALOR6FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR7 {
            get {
                return this.vALOR7Field;
            }
            set {
                this.vALOR7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR7Specified {
            get {
                return this.vALOR7FieldSpecified;
            }
            set {
                this.vALOR7FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR8 {
            get {
                return this.vALOR8Field;
            }
            set {
                this.vALOR8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR8Specified {
            get {
                return this.vALOR8FieldSpecified;
            }
            set {
                this.vALOR8FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int VALOR9 {
            get {
                return this.vALOR9Field;
            }
            set {
                this.vALOR9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR9Specified {
            get {
                return this.vALOR9FieldSpecified;
            }
            set {
                this.vALOR9FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void listarAccesosPorDiaCompletedEventHandler(object sender, listarAccesosPorDiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarAccesosPorDiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarAccesosPorDiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public enAcceso[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((enAcceso[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void enviarAccesoCompletedEventHandler(object sender, enviarAccesoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarAccesoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarAccesoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public coResultadoDB Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((coResultadoDB)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void enviarAccesoUltCompletedEventHandler(object sender, enviarAccesoUltCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarAccesoUltCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarAccesoUltCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public coResultadoDB Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((coResultadoDB)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591