//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.servicioPide {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWCFIntegracionPide", Namespace="http://tempuri.org/")]
    public partial class WCFIntegracionPide : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback verificaPersonaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFIntegracionPide() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_servicioPide_WCFIntegracionPide;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event verificaPersonaCompletedEventHandler verificaPersonaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFIntegracionPide/verificaPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultadoPersona verificaPersona([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] IntegracionVerificaPersona oEnPersona) {
            object[] results = this.Invoke("verificaPersona", new object[] {
                        oEnPersona});
            return ((ResultadoPersona)(results[0]));
        }
        
        /// <remarks/>
        public void verificaPersonaAsync(IntegracionVerificaPersona oEnPersona) {
            this.verificaPersonaAsync(oEnPersona, null);
        }
        
        /// <remarks/>
        public void verificaPersonaAsync(IntegracionVerificaPersona oEnPersona, object userState) {
            if ((this.verificaPersonaOperationCompleted == null)) {
                this.verificaPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificaPersonaOperationCompleted);
            }
            this.InvokeAsync("verificaPersona", new object[] {
                        oEnPersona}, this.verificaPersonaOperationCompleted, userState);
        }
        
        private void OnverificaPersonaOperationCompleted(object arg) {
            if ((this.verificaPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificaPersonaCompleted(this, new verificaPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Mincetur.Administracion.Integracion.ServicioIntegracion")]
    public partial class IntegracionVerificaPersona {
        
        private string tipoPersonaField;
        
        private string rucField;
        
        private int idDocuField;
        
        private bool idDocuFieldSpecified;
        
        private string numDocuField;
        
        private int oprField;
        
        private bool oprFieldSpecified;
        
        private int idUsuField;
        
        private bool idUsuFieldSpecified;
        
        private int idSisField;
        
        private bool idSisFieldSpecified;
        
        private string ipAccesoField;
        
        private int flgRegistroField;
        
        private bool flgRegistroFieldSpecified;
        
        private int flgServicioField;
        
        private bool flgServicioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
            }
        }
        
        /// <remarks/>
        public int IdDocu {
            get {
                return this.idDocuField;
            }
            set {
                this.idDocuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdDocuSpecified {
            get {
                return this.idDocuFieldSpecified;
            }
            set {
                this.idDocuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumDocu {
            get {
                return this.numDocuField;
            }
            set {
                this.numDocuField = value;
            }
        }
        
        /// <remarks/>
        public int Opr {
            get {
                return this.oprField;
            }
            set {
                this.oprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OprSpecified {
            get {
                return this.oprFieldSpecified;
            }
            set {
                this.oprFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdUsu {
            get {
                return this.idUsuField;
            }
            set {
                this.idUsuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUsuSpecified {
            get {
                return this.idUsuFieldSpecified;
            }
            set {
                this.idUsuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdSis {
            get {
                return this.idSisField;
            }
            set {
                this.idSisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSisSpecified {
            get {
                return this.idSisFieldSpecified;
            }
            set {
                this.idSisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IpAcceso {
            get {
                return this.ipAccesoField;
            }
            set {
                this.ipAccesoField = value;
            }
        }
        
        /// <remarks/>
        public int FlgRegistro {
            get {
                return this.flgRegistroField;
            }
            set {
                this.flgRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgRegistroSpecified {
            get {
                return this.flgRegistroFieldSpecified;
            }
            set {
                this.flgRegistroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int FlgServicio {
            get {
                return this.flgServicioField;
            }
            set {
                this.flgServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgServicioSpecified {
            get {
                return this.flgServicioFieldSpecified;
            }
            set {
                this.flgServicioFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Mincetur.Administracion.Integracion.ServicioIntegracion")]
    public partial class DatosPersona {
        
        private int idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string rucField;
        
        private string tipoPersonaField;
        
        private int flgNoDomiciliadoField;
        
        private bool flgNoDomiciliadoFieldSpecified;
        
        private int idPaisField;
        
        private bool idPaisFieldSpecified;
        
        private string nombresField;
        
        private string apePaterField;
        
        private string apeMaterField;
        
        private string nomPersonaField;
        
        private int idGeneroField;
        
        private bool idGeneroFieldSpecified;
        
        private int idDocuField;
        
        private bool idDocuFieldSpecified;
        
        private string desDocuField;
        
        private string abrDocuField;
        
        private string numDocuField;
        
        private int idDomiField;
        
        private bool idDomiFieldSpecified;
        
        private string abrGeneroField;
        
        private System.Nullable<int> idViaField;
        
        private bool idViaFieldSpecified;
        
        private string desViaField;
        
        private string numeroField;
        
        private string interiorField;
        
        private int idZonaField;
        
        private bool idZonaFieldSpecified;
        
        private string desZonaField;
        
        private string obsDomicilioField;
        
        private int idUbigeoField;
        
        private bool idUbigeoFieldSpecified;
        
        private string codUbigeoField;
        
        private System.DateTime fecNacField;
        
        private bool fecNacFieldSpecified;
        
        private int flgVerificadoField;
        
        private bool flgVerificadoFieldSpecified;
        
        private int flgEstField;
        
        private bool flgEstFieldSpecified;
        
        private string razonSocialField;
        
        private string nombreComercialField;
        
        private string estadoCivilField;
        
        private int idPerDocuField;
        
        private bool idPerDocuFieldSpecified;
        
        private int flgServicioField;
        
        private bool flgServicioFieldSpecified;
        
        private int flgInDataField;
        
        private bool flgInDataFieldSpecified;
        
        private string desUbigeoField;
        
        private string restriccionField;
        
        private byte[] fotoField;
        
        private int flgReniecField;
        
        private bool flgReniecFieldSpecified;
        
        /// <remarks/>
        public int IdPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        public int FlgNoDomiciliado {
            get {
                return this.flgNoDomiciliadoField;
            }
            set {
                this.flgNoDomiciliadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgNoDomiciliadoSpecified {
            get {
                return this.flgNoDomiciliadoFieldSpecified;
            }
            set {
                this.flgNoDomiciliadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdPais {
            get {
                return this.idPaisField;
            }
            set {
                this.idPaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdPaisSpecified {
            get {
                return this.idPaisFieldSpecified;
            }
            set {
                this.idPaisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApePater {
            get {
                return this.apePaterField;
            }
            set {
                this.apePaterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApeMater {
            get {
                return this.apeMaterField;
            }
            set {
                this.apeMaterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NomPersona {
            get {
                return this.nomPersonaField;
            }
            set {
                this.nomPersonaField = value;
            }
        }
        
        /// <remarks/>
        public int IdGenero {
            get {
                return this.idGeneroField;
            }
            set {
                this.idGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdGeneroSpecified {
            get {
                return this.idGeneroFieldSpecified;
            }
            set {
                this.idGeneroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdDocu {
            get {
                return this.idDocuField;
            }
            set {
                this.idDocuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdDocuSpecified {
            get {
                return this.idDocuFieldSpecified;
            }
            set {
                this.idDocuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesDocu {
            get {
                return this.desDocuField;
            }
            set {
                this.desDocuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbrDocu {
            get {
                return this.abrDocuField;
            }
            set {
                this.abrDocuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumDocu {
            get {
                return this.numDocuField;
            }
            set {
                this.numDocuField = value;
            }
        }
        
        /// <remarks/>
        public int IdDomi {
            get {
                return this.idDomiField;
            }
            set {
                this.idDomiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdDomiSpecified {
            get {
                return this.idDomiFieldSpecified;
            }
            set {
                this.idDomiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbrGenero {
            get {
                return this.abrGeneroField;
            }
            set {
                this.abrGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdVia {
            get {
                return this.idViaField;
            }
            set {
                this.idViaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdViaSpecified {
            get {
                return this.idViaFieldSpecified;
            }
            set {
                this.idViaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesVia {
            get {
                return this.desViaField;
            }
            set {
                this.desViaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Interior {
            get {
                return this.interiorField;
            }
            set {
                this.interiorField = value;
            }
        }
        
        /// <remarks/>
        public int IdZona {
            get {
                return this.idZonaField;
            }
            set {
                this.idZonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdZonaSpecified {
            get {
                return this.idZonaFieldSpecified;
            }
            set {
                this.idZonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesZona {
            get {
                return this.desZonaField;
            }
            set {
                this.desZonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ObsDomicilio {
            get {
                return this.obsDomicilioField;
            }
            set {
                this.obsDomicilioField = value;
            }
        }
        
        /// <remarks/>
        public int IdUbigeo {
            get {
                return this.idUbigeoField;
            }
            set {
                this.idUbigeoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUbigeoSpecified {
            get {
                return this.idUbigeoFieldSpecified;
            }
            set {
                this.idUbigeoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodUbigeo {
            get {
                return this.codUbigeoField;
            }
            set {
                this.codUbigeoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FecNac {
            get {
                return this.fecNacField;
            }
            set {
                this.fecNacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FecNacSpecified {
            get {
                return this.fecNacFieldSpecified;
            }
            set {
                this.fecNacFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int FlgVerificado {
            get {
                return this.flgVerificadoField;
            }
            set {
                this.flgVerificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgVerificadoSpecified {
            get {
                return this.flgVerificadoFieldSpecified;
            }
            set {
                this.flgVerificadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int FlgEst {
            get {
                return this.flgEstField;
            }
            set {
                this.flgEstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgEstSpecified {
            get {
                return this.flgEstFieldSpecified;
            }
            set {
                this.flgEstFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                this.nombreComercialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EstadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        public int IdPerDocu {
            get {
                return this.idPerDocuField;
            }
            set {
                this.idPerDocuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdPerDocuSpecified {
            get {
                return this.idPerDocuFieldSpecified;
            }
            set {
                this.idPerDocuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int FlgServicio {
            get {
                return this.flgServicioField;
            }
            set {
                this.flgServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgServicioSpecified {
            get {
                return this.flgServicioFieldSpecified;
            }
            set {
                this.flgServicioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int FlgInData {
            get {
                return this.flgInDataField;
            }
            set {
                this.flgInDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgInDataSpecified {
            get {
                return this.flgInDataFieldSpecified;
            }
            set {
                this.flgInDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesUbigeo {
            get {
                return this.desUbigeoField;
            }
            set {
                this.desUbigeoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Restriccion {
            get {
                return this.restriccionField;
            }
            set {
                this.restriccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        public int FlgReniec {
            get {
                return this.flgReniecField;
            }
            set {
                this.flgReniecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgReniecSpecified {
            get {
                return this.flgReniecFieldSpecified;
            }
            set {
                this.flgReniecFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Mincetur.Administracion.Integracion.ServicioIntegracion")]
    public partial class ResultadoPersona {
        
        private int idTipoField;
        
        private bool idTipoFieldSpecified;
        
        private string idErrorField;
        
        private string desErrorField;
        
        private string idErrorDbField;
        
        private int valorField;
        
        private bool valorFieldSpecified;
        
        private string valor1Field;
        
        private string valor2Field;
        
        private string valor3Field;
        
        private string valor4Field;
        
        private string valor5Field;
        
        private string valor6Field;
        
        private string valor7Field;
        
        private string valor8Field;
        
        private string valor9Field;
        
        private string valor10Field;
        
        private DatosPersona datosPersonaField;
        
        /// <remarks/>
        public int IdTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdTipoSpecified {
            get {
                return this.idTipoFieldSpecified;
            }
            set {
                this.idTipoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdError {
            get {
                return this.idErrorField;
            }
            set {
                this.idErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesError {
            get {
                return this.desErrorField;
            }
            set {
                this.desErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdErrorDb {
            get {
                return this.idErrorDbField;
            }
            set {
                this.idErrorDbField = value;
            }
        }
        
        /// <remarks/>
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor1 {
            get {
                return this.valor1Field;
            }
            set {
                this.valor1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor2 {
            get {
                return this.valor2Field;
            }
            set {
                this.valor2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor3 {
            get {
                return this.valor3Field;
            }
            set {
                this.valor3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor4 {
            get {
                return this.valor4Field;
            }
            set {
                this.valor4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor5 {
            get {
                return this.valor5Field;
            }
            set {
                this.valor5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor6 {
            get {
                return this.valor6Field;
            }
            set {
                this.valor6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor7 {
            get {
                return this.valor7Field;
            }
            set {
                this.valor7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor8 {
            get {
                return this.valor8Field;
            }
            set {
                this.valor8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor9 {
            get {
                return this.valor9Field;
            }
            set {
                this.valor9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor10 {
            get {
                return this.valor10Field;
            }
            set {
                this.valor10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DatosPersona DatosPersona {
            get {
                return this.datosPersonaField;
            }
            set {
                this.datosPersonaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void verificaPersonaCompletedEventHandler(object sender, verificaPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificaPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificaPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoPersona Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoPersona)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591