//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.servicioSunatContribuyente {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsContribuyenteSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coHBase))]
    public partial class wsContribuyente : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listarContribuyentesOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarContribuyentes3OperationCompleted;
        
        private System.Threading.SendOrPostCallback listarContribuyentes2OperationCompleted;
        
        private System.Threading.SendOrPostCallback listarRepresentanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarEstablecimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarEstadoContribuyenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback estadoValidaSunatOperationCompleted;
        
        private System.Threading.SendOrPostCallback validarNumDocumentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsContribuyente() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_ServicioSunatContribuyente_wsContribuyente;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listarContribuyentesCompletedEventHandler listarContribuyentesCompleted;
        
        /// <remarks/>
        public event listarContribuyentes3CompletedEventHandler listarContribuyentes3Completed;
        
        /// <remarks/>
        public event listarContribuyentes2CompletedEventHandler listarContribuyentes2Completed;
        
        /// <remarks/>
        public event listarRepresentanteCompletedEventHandler listarRepresentanteCompleted;
        
        /// <remarks/>
        public event listarEstablecimientoCompletedEventHandler listarEstablecimientoCompleted;
        
        /// <remarks/>
        public event listarEstadoContribuyenteCompletedEventHandler listarEstadoContribuyenteCompleted;
        
        /// <remarks/>
        public event estadoValidaSunatCompletedEventHandler estadoValidaSunatCompleted;
        
        /// <remarks/>
        public event validarNumDocumentoCompletedEventHandler validarNumDocumentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarContribuyentes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public enContribuyente[] listarContribuyentes(enContribuyente objEnContribuyente) {
            object[] results = this.Invoke("listarContribuyentes", new object[] {
                        objEnContribuyente});
            return ((enContribuyente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarContribuyentesAsync(enContribuyente objEnContribuyente) {
            this.listarContribuyentesAsync(objEnContribuyente, null);
        }
        
        /// <remarks/>
        public void listarContribuyentesAsync(enContribuyente objEnContribuyente, object userState) {
            if ((this.listarContribuyentesOperationCompleted == null)) {
                this.listarContribuyentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarContribuyentesOperationCompleted);
            }
            this.InvokeAsync("listarContribuyentes", new object[] {
                        objEnContribuyente}, this.listarContribuyentesOperationCompleted, userState);
        }
        
        private void OnlistarContribuyentesOperationCompleted(object arg) {
            if ((this.listarContribuyentesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarContribuyentesCompleted(this, new listarContribuyentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarContribuyentes3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public enContribuyente[] listarContribuyentes3(enContribuyente objEnContribuyente) {
            object[] results = this.Invoke("listarContribuyentes3", new object[] {
                        objEnContribuyente});
            return ((enContribuyente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarContribuyentes3Async(enContribuyente objEnContribuyente) {
            this.listarContribuyentes3Async(objEnContribuyente, null);
        }
        
        /// <remarks/>
        public void listarContribuyentes3Async(enContribuyente objEnContribuyente, object userState) {
            if ((this.listarContribuyentes3OperationCompleted == null)) {
                this.listarContribuyentes3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarContribuyentes3OperationCompleted);
            }
            this.InvokeAsync("listarContribuyentes3", new object[] {
                        objEnContribuyente}, this.listarContribuyentes3OperationCompleted, userState);
        }
        
        private void OnlistarContribuyentes3OperationCompleted(object arg) {
            if ((this.listarContribuyentes3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarContribuyentes3Completed(this, new listarContribuyentes3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarContribuyentes2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public enContribuyente[] listarContribuyentes2(string DDP_NUMRUC, string FLG_EST, string OPR) {
            object[] results = this.Invoke("listarContribuyentes2", new object[] {
                        DDP_NUMRUC,
                        FLG_EST,
                        OPR});
            return ((enContribuyente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarContribuyentes2Async(string DDP_NUMRUC, string FLG_EST, string OPR) {
            this.listarContribuyentes2Async(DDP_NUMRUC, FLG_EST, OPR, null);
        }
        
        /// <remarks/>
        public void listarContribuyentes2Async(string DDP_NUMRUC, string FLG_EST, string OPR, object userState) {
            if ((this.listarContribuyentes2OperationCompleted == null)) {
                this.listarContribuyentes2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarContribuyentes2OperationCompleted);
            }
            this.InvokeAsync("listarContribuyentes2", new object[] {
                        DDP_NUMRUC,
                        FLG_EST,
                        OPR}, this.listarContribuyentes2OperationCompleted, userState);
        }
        
        private void OnlistarContribuyentes2OperationCompleted(object arg) {
            if ((this.listarContribuyentes2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarContribuyentes2Completed(this, new listarContribuyentes2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarRepresentante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public enContribuyente[] listarRepresentante(enContribuyente objEnContribuyente) {
            object[] results = this.Invoke("listarRepresentante", new object[] {
                        objEnContribuyente});
            return ((enContribuyente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarRepresentanteAsync(enContribuyente objEnContribuyente) {
            this.listarRepresentanteAsync(objEnContribuyente, null);
        }
        
        /// <remarks/>
        public void listarRepresentanteAsync(enContribuyente objEnContribuyente, object userState) {
            if ((this.listarRepresentanteOperationCompleted == null)) {
                this.listarRepresentanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarRepresentanteOperationCompleted);
            }
            this.InvokeAsync("listarRepresentante", new object[] {
                        objEnContribuyente}, this.listarRepresentanteOperationCompleted, userState);
        }
        
        private void OnlistarRepresentanteOperationCompleted(object arg) {
            if ((this.listarRepresentanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarRepresentanteCompleted(this, new listarRepresentanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarEstablecimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public enContribuyente[] listarEstablecimiento(enContribuyente objEnContribuyente) {
            object[] results = this.Invoke("listarEstablecimiento", new object[] {
                        objEnContribuyente});
            return ((enContribuyente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarEstablecimientoAsync(enContribuyente objEnContribuyente) {
            this.listarEstablecimientoAsync(objEnContribuyente, null);
        }
        
        /// <remarks/>
        public void listarEstablecimientoAsync(enContribuyente objEnContribuyente, object userState) {
            if ((this.listarEstablecimientoOperationCompleted == null)) {
                this.listarEstablecimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarEstablecimientoOperationCompleted);
            }
            this.InvokeAsync("listarEstablecimiento", new object[] {
                        objEnContribuyente}, this.listarEstablecimientoOperationCompleted, userState);
        }
        
        private void OnlistarEstablecimientoOperationCompleted(object arg) {
            if ((this.listarEstablecimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarEstablecimientoCompleted(this, new listarEstablecimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarEstadoContribuyente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public enContribuyente[] listarEstadoContribuyente(enContribuyente objEnContribuyente) {
            object[] results = this.Invoke("listarEstadoContribuyente", new object[] {
                        objEnContribuyente});
            return ((enContribuyente[])(results[0]));
        }
        
        /// <remarks/>
        public void listarEstadoContribuyenteAsync(enContribuyente objEnContribuyente) {
            this.listarEstadoContribuyenteAsync(objEnContribuyente, null);
        }
        
        /// <remarks/>
        public void listarEstadoContribuyenteAsync(enContribuyente objEnContribuyente, object userState) {
            if ((this.listarEstadoContribuyenteOperationCompleted == null)) {
                this.listarEstadoContribuyenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarEstadoContribuyenteOperationCompleted);
            }
            this.InvokeAsync("listarEstadoContribuyente", new object[] {
                        objEnContribuyente}, this.listarEstadoContribuyenteOperationCompleted, userState);
        }
        
        private void OnlistarEstadoContribuyenteOperationCompleted(object arg) {
            if ((this.listarEstadoContribuyenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarEstadoContribuyenteCompleted(this, new listarEstadoContribuyenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/estadoValidaSunat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string estadoValidaSunat(enContribuyente objEnContribuyente) {
            object[] results = this.Invoke("estadoValidaSunat", new object[] {
                        objEnContribuyente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void estadoValidaSunatAsync(enContribuyente objEnContribuyente) {
            this.estadoValidaSunatAsync(objEnContribuyente, null);
        }
        
        /// <remarks/>
        public void estadoValidaSunatAsync(enContribuyente objEnContribuyente, object userState) {
            if ((this.estadoValidaSunatOperationCompleted == null)) {
                this.estadoValidaSunatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnestadoValidaSunatOperationCompleted);
            }
            this.InvokeAsync("estadoValidaSunat", new object[] {
                        objEnContribuyente}, this.estadoValidaSunatOperationCompleted, userState);
        }
        
        private void OnestadoValidaSunatOperationCompleted(object arg) {
            if ((this.estadoValidaSunatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.estadoValidaSunatCompleted(this, new estadoValidaSunatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validarNumDocumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public enContribuyente[] validarNumDocumento(enContribuyente objEnContribuyente) {
            object[] results = this.Invoke("validarNumDocumento", new object[] {
                        objEnContribuyente});
            return ((enContribuyente[])(results[0]));
        }
        
        /// <remarks/>
        public void validarNumDocumentoAsync(enContribuyente objEnContribuyente) {
            this.validarNumDocumentoAsync(objEnContribuyente, null);
        }
        
        /// <remarks/>
        public void validarNumDocumentoAsync(enContribuyente objEnContribuyente, object userState) {
            if ((this.validarNumDocumentoOperationCompleted == null)) {
                this.validarNumDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarNumDocumentoOperationCompleted);
            }
            this.InvokeAsync("validarNumDocumento", new object[] {
                        objEnContribuyente}, this.validarNumDocumentoOperationCompleted, userState);
        }
        
        private void OnvalidarNumDocumentoOperationCompleted(object arg) {
            if ((this.validarNumDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarNumDocumentoCompleted(this, new validarNumDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class enContribuyente : coHBase {
        
        private string dDP_NOMBREField;
        
        private string dDP_NUMRUCField;
        
        private string dDP_NUMREGField;
        
        private string dES_DEPENDENCIAField;
        
        private string dDP_TPOEMPField;
        
        private string dES_TPOEMPRESAField;
        
        private string dDP_TAMANOField;
        
        private string dES_TAMANOField;
        
        private string dDP_IDENTIField;
        
        private string dES_TPOPERSONAField;
        
        private string dDP_CIIUField;
        
        private string dES_CIIUField;
        
        private string dES_CIIU_SECField;
        
        private string dES_CIIU_TERField;
        
        private string dDP_UBIGEOField;
        
        private string dES_UBIGEOField;
        
        private string dDP_NOMVIAField;
        
        private string dDP_NUMER1Field;
        
        private string dDP_INTER1Field;
        
        private string dDP_NOMZONField;
        
        private string dDP_REFER1Field;
        
        private string dDP_FLAG22Field;
        
        private string dES_DOMICILIOFISCALField;
        
        private string dDP_ESTADOField;
        
        private string dES_ESTADOField;
        
        private string cOD_ESTADOField;
        
        private string dDP_FECALTField;
        
        private string dDP_FECBAJField;
        
        private string dDP_TIPVIAField;
        
        private string dES_TPOVIAField;
        
        private string dDP_TIPZONField;
        
        private string dES_TPOZONAField;
        
        private string dES_DIRECCIONField;
        
        private string fEC_CREA1Field;
        
        private string fEC_MODI1Field;
        
        private string rSO_NRODOCField;
        
        private string rSO_CARGOField;
        
        private string rSO_DOCIDEField;
        
        private string dES_DOCIDEField;
        
        private string sPR_CORRELField;
        
        private string sPR_TIPESTField;
        
        private string dES_TIPESTField;
        
        private string dDS_INICIOField;
        
        private string dDS_NRODOCField;
        
        private string dES_TIPDOCField;
        
        private string dDS_INIField;
        
        private string dDS_FINField;
        
        /// <remarks/>
        public string DDP_NOMBRE {
            get {
                return this.dDP_NOMBREField;
            }
            set {
                this.dDP_NOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_NUMRUC {
            get {
                return this.dDP_NUMRUCField;
            }
            set {
                this.dDP_NUMRUCField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_NUMREG {
            get {
                return this.dDP_NUMREGField;
            }
            set {
                this.dDP_NUMREGField = value;
            }
        }
        
        /// <remarks/>
        public string DES_DEPENDENCIA {
            get {
                return this.dES_DEPENDENCIAField;
            }
            set {
                this.dES_DEPENDENCIAField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_TPOEMP {
            get {
                return this.dDP_TPOEMPField;
            }
            set {
                this.dDP_TPOEMPField = value;
            }
        }
        
        /// <remarks/>
        public string DES_TPOEMPRESA {
            get {
                return this.dES_TPOEMPRESAField;
            }
            set {
                this.dES_TPOEMPRESAField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_TAMANO {
            get {
                return this.dDP_TAMANOField;
            }
            set {
                this.dDP_TAMANOField = value;
            }
        }
        
        /// <remarks/>
        public string DES_TAMANO {
            get {
                return this.dES_TAMANOField;
            }
            set {
                this.dES_TAMANOField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_IDENTI {
            get {
                return this.dDP_IDENTIField;
            }
            set {
                this.dDP_IDENTIField = value;
            }
        }
        
        /// <remarks/>
        public string DES_TPOPERSONA {
            get {
                return this.dES_TPOPERSONAField;
            }
            set {
                this.dES_TPOPERSONAField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_CIIU {
            get {
                return this.dDP_CIIUField;
            }
            set {
                this.dDP_CIIUField = value;
            }
        }
        
        /// <remarks/>
        public string DES_CIIU {
            get {
                return this.dES_CIIUField;
            }
            set {
                this.dES_CIIUField = value;
            }
        }
        
        /// <remarks/>
        public string DES_CIIU_SEC {
            get {
                return this.dES_CIIU_SECField;
            }
            set {
                this.dES_CIIU_SECField = value;
            }
        }
        
        /// <remarks/>
        public string DES_CIIU_TER {
            get {
                return this.dES_CIIU_TERField;
            }
            set {
                this.dES_CIIU_TERField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_UBIGEO {
            get {
                return this.dDP_UBIGEOField;
            }
            set {
                this.dDP_UBIGEOField = value;
            }
        }
        
        /// <remarks/>
        public string DES_UBIGEO {
            get {
                return this.dES_UBIGEOField;
            }
            set {
                this.dES_UBIGEOField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_NOMVIA {
            get {
                return this.dDP_NOMVIAField;
            }
            set {
                this.dDP_NOMVIAField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_NUMER1 {
            get {
                return this.dDP_NUMER1Field;
            }
            set {
                this.dDP_NUMER1Field = value;
            }
        }
        
        /// <remarks/>
        public string DDP_INTER1 {
            get {
                return this.dDP_INTER1Field;
            }
            set {
                this.dDP_INTER1Field = value;
            }
        }
        
        /// <remarks/>
        public string DDP_NOMZON {
            get {
                return this.dDP_NOMZONField;
            }
            set {
                this.dDP_NOMZONField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_REFER1 {
            get {
                return this.dDP_REFER1Field;
            }
            set {
                this.dDP_REFER1Field = value;
            }
        }
        
        /// <remarks/>
        public string DDP_FLAG22 {
            get {
                return this.dDP_FLAG22Field;
            }
            set {
                this.dDP_FLAG22Field = value;
            }
        }
        
        /// <remarks/>
        public string DES_DOMICILIOFISCAL {
            get {
                return this.dES_DOMICILIOFISCALField;
            }
            set {
                this.dES_DOMICILIOFISCALField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_ESTADO {
            get {
                return this.dDP_ESTADOField;
            }
            set {
                this.dDP_ESTADOField = value;
            }
        }
        
        /// <remarks/>
        public string DES_ESTADO {
            get {
                return this.dES_ESTADOField;
            }
            set {
                this.dES_ESTADOField = value;
            }
        }
        
        /// <remarks/>
        public string COD_ESTADO {
            get {
                return this.cOD_ESTADOField;
            }
            set {
                this.cOD_ESTADOField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_FECALT {
            get {
                return this.dDP_FECALTField;
            }
            set {
                this.dDP_FECALTField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_FECBAJ {
            get {
                return this.dDP_FECBAJField;
            }
            set {
                this.dDP_FECBAJField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_TIPVIA {
            get {
                return this.dDP_TIPVIAField;
            }
            set {
                this.dDP_TIPVIAField = value;
            }
        }
        
        /// <remarks/>
        public string DES_TPOVIA {
            get {
                return this.dES_TPOVIAField;
            }
            set {
                this.dES_TPOVIAField = value;
            }
        }
        
        /// <remarks/>
        public string DDP_TIPZON {
            get {
                return this.dDP_TIPZONField;
            }
            set {
                this.dDP_TIPZONField = value;
            }
        }
        
        /// <remarks/>
        public string DES_TPOZONA {
            get {
                return this.dES_TPOZONAField;
            }
            set {
                this.dES_TPOZONAField = value;
            }
        }
        
        /// <remarks/>
        public string DES_DIRECCION {
            get {
                return this.dES_DIRECCIONField;
            }
            set {
                this.dES_DIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        public string FEC_CREA1 {
            get {
                return this.fEC_CREA1Field;
            }
            set {
                this.fEC_CREA1Field = value;
            }
        }
        
        /// <remarks/>
        public string FEC_MODI1 {
            get {
                return this.fEC_MODI1Field;
            }
            set {
                this.fEC_MODI1Field = value;
            }
        }
        
        /// <remarks/>
        public string RSO_NRODOC {
            get {
                return this.rSO_NRODOCField;
            }
            set {
                this.rSO_NRODOCField = value;
            }
        }
        
        /// <remarks/>
        public string RSO_CARGO {
            get {
                return this.rSO_CARGOField;
            }
            set {
                this.rSO_CARGOField = value;
            }
        }
        
        /// <remarks/>
        public string RSO_DOCIDE {
            get {
                return this.rSO_DOCIDEField;
            }
            set {
                this.rSO_DOCIDEField = value;
            }
        }
        
        /// <remarks/>
        public string DES_DOCIDE {
            get {
                return this.dES_DOCIDEField;
            }
            set {
                this.dES_DOCIDEField = value;
            }
        }
        
        /// <remarks/>
        public string SPR_CORREL {
            get {
                return this.sPR_CORRELField;
            }
            set {
                this.sPR_CORRELField = value;
            }
        }
        
        /// <remarks/>
        public string SPR_TIPEST {
            get {
                return this.sPR_TIPESTField;
            }
            set {
                this.sPR_TIPESTField = value;
            }
        }
        
        /// <remarks/>
        public string DES_TIPEST {
            get {
                return this.dES_TIPESTField;
            }
            set {
                this.dES_TIPESTField = value;
            }
        }
        
        /// <remarks/>
        public string DDS_INICIO {
            get {
                return this.dDS_INICIOField;
            }
            set {
                this.dDS_INICIOField = value;
            }
        }
        
        /// <remarks/>
        public string DDS_NRODOC {
            get {
                return this.dDS_NRODOCField;
            }
            set {
                this.dDS_NRODOCField = value;
            }
        }
        
        /// <remarks/>
        public string DES_TIPDOC {
            get {
                return this.dES_TIPDOCField;
            }
            set {
                this.dES_TIPDOCField = value;
            }
        }
        
        /// <remarks/>
        public string DDS_INI {
            get {
                return this.dDS_INIField;
            }
            set {
                this.dDS_INIField = value;
            }
        }
        
        /// <remarks/>
        public string DDS_FIN {
            get {
                return this.dDS_FINField;
            }
            set {
                this.dDS_FINField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enContribuyente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class coHBase {
        
        private int fLG_ESTField;
        
        private string dES_ESTField;
        
        private string fLG_STR_ESTField;
        
        private System.DateTime fEC_INIField;
        
        private System.DateTime fEC_FINField;
        
        private System.DateTime fEC_MODIField;
        
        private int uSU_CREAField;
        
        private string dES_USU_CREAField;
        
        private int uSU_MODIField;
        
        private string dES_USU_MODIField;
        
        private int iD_USUField;
        
        private int iD_SISField;
        
        private string dES_SIS_CREAField;
        
        private string dES_SIS_MODIField;
        
        private string ipField;
        
        private int cANTIDADField;
        
        private string oPRField;
        
        private int cORRField;
        
        private string dATOField;
        
        /// <remarks/>
        public int FLG_EST {
            get {
                return this.fLG_ESTField;
            }
            set {
                this.fLG_ESTField = value;
            }
        }
        
        /// <remarks/>
        public string DES_EST {
            get {
                return this.dES_ESTField;
            }
            set {
                this.dES_ESTField = value;
            }
        }
        
        /// <remarks/>
        public string FLG_STR_EST {
            get {
                return this.fLG_STR_ESTField;
            }
            set {
                this.fLG_STR_ESTField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FEC_INI {
            get {
                return this.fEC_INIField;
            }
            set {
                this.fEC_INIField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FEC_FIN {
            get {
                return this.fEC_FINField;
            }
            set {
                this.fEC_FINField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FEC_MODI {
            get {
                return this.fEC_MODIField;
            }
            set {
                this.fEC_MODIField = value;
            }
        }
        
        /// <remarks/>
        public int USU_CREA {
            get {
                return this.uSU_CREAField;
            }
            set {
                this.uSU_CREAField = value;
            }
        }
        
        /// <remarks/>
        public string DES_USU_CREA {
            get {
                return this.dES_USU_CREAField;
            }
            set {
                this.dES_USU_CREAField = value;
            }
        }
        
        /// <remarks/>
        public int USU_MODI {
            get {
                return this.uSU_MODIField;
            }
            set {
                this.uSU_MODIField = value;
            }
        }
        
        /// <remarks/>
        public string DES_USU_MODI {
            get {
                return this.dES_USU_MODIField;
            }
            set {
                this.dES_USU_MODIField = value;
            }
        }
        
        /// <remarks/>
        public int ID_USU {
            get {
                return this.iD_USUField;
            }
            set {
                this.iD_USUField = value;
            }
        }
        
        /// <remarks/>
        public int ID_SIS {
            get {
                return this.iD_SISField;
            }
            set {
                this.iD_SISField = value;
            }
        }
        
        /// <remarks/>
        public string DES_SIS_CREA {
            get {
                return this.dES_SIS_CREAField;
            }
            set {
                this.dES_SIS_CREAField = value;
            }
        }
        
        /// <remarks/>
        public string DES_SIS_MODI {
            get {
                return this.dES_SIS_MODIField;
            }
            set {
                this.dES_SIS_MODIField = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public int CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
        
        /// <remarks/>
        public string OPR {
            get {
                return this.oPRField;
            }
            set {
                this.oPRField = value;
            }
        }
        
        /// <remarks/>
        public int CORR {
            get {
                return this.cORRField;
            }
            set {
                this.cORRField = value;
            }
        }
        
        /// <remarks/>
        public string DATO {
            get {
                return this.dATOField;
            }
            set {
                this.dATOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void listarContribuyentesCompletedEventHandler(object sender, listarContribuyentesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarContribuyentesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarContribuyentesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public enContribuyente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((enContribuyente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void listarContribuyentes3CompletedEventHandler(object sender, listarContribuyentes3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarContribuyentes3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarContribuyentes3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public enContribuyente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((enContribuyente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void listarContribuyentes2CompletedEventHandler(object sender, listarContribuyentes2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarContribuyentes2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarContribuyentes2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public enContribuyente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((enContribuyente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void listarRepresentanteCompletedEventHandler(object sender, listarRepresentanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarRepresentanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarRepresentanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public enContribuyente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((enContribuyente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void listarEstablecimientoCompletedEventHandler(object sender, listarEstablecimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarEstablecimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarEstablecimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public enContribuyente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((enContribuyente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void listarEstadoContribuyenteCompletedEventHandler(object sender, listarEstadoContribuyenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarEstadoContribuyenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarEstadoContribuyenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public enContribuyente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((enContribuyente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void estadoValidaSunatCompletedEventHandler(object sender, estadoValidaSunatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class estadoValidaSunatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal estadoValidaSunatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void validarNumDocumentoCompletedEventHandler(object sender, validarNumDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarNumDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarNumDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public enContribuyente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((enContribuyente[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591