//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.soap.ServicioArchivoLaserfiche {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWCFEIArchivoLF", Namespace="http://tempuri.org/")]
    public partial class WCFEIArchivoLF : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DescargarArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportarArchivoByteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubirArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubirArchivoMasivoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFEIArchivoLF() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_soap_ServicioArchivoLaserfiche_WCFEIArchivoLF;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DescargarArchivoCompletedEventHandler DescargarArchivoCompleted;
        
        /// <remarks/>
        public event ExportarArchivoByteCompletedEventHandler ExportarArchivoByteCompleted;
        
        /// <remarks/>
        public event SubirArchivoCompletedEventHandler SubirArchivoCompleted;
        
        /// <remarks/>
        public event SubirArchivoMasivoCompletedEventHandler SubirArchivoMasivoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFEIArchivoLF/DescargarArchivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultExportarArch DescargarArchivo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DatosDescargarArchivo dataExportar) {
            object[] results = this.Invoke("DescargarArchivo", new object[] {
                        dataExportar});
            return ((ResultExportarArch)(results[0]));
        }
        
        /// <remarks/>
        public void DescargarArchivoAsync(DatosDescargarArchivo dataExportar) {
            this.DescargarArchivoAsync(dataExportar, null);
        }
        
        /// <remarks/>
        public void DescargarArchivoAsync(DatosDescargarArchivo dataExportar, object userState) {
            if ((this.DescargarArchivoOperationCompleted == null)) {
                this.DescargarArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDescargarArchivoOperationCompleted);
            }
            this.InvokeAsync("DescargarArchivo", new object[] {
                        dataExportar}, this.DescargarArchivoOperationCompleted, userState);
        }
        
        private void OnDescargarArchivoOperationCompleted(object arg) {
            if ((this.DescargarArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DescargarArchivoCompleted(this, new DescargarArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFEIArchivoLF/ExportarArchivoByte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultExportarArchByte ExportarArchivoByte([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DatosExportarArchByte dataExportar) {
            object[] results = this.Invoke("ExportarArchivoByte", new object[] {
                        dataExportar});
            return ((ResultExportarArchByte)(results[0]));
        }
        
        /// <remarks/>
        public void ExportarArchivoByteAsync(DatosExportarArchByte dataExportar) {
            this.ExportarArchivoByteAsync(dataExportar, null);
        }
        
        /// <remarks/>
        public void ExportarArchivoByteAsync(DatosExportarArchByte dataExportar, object userState) {
            if ((this.ExportarArchivoByteOperationCompleted == null)) {
                this.ExportarArchivoByteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportarArchivoByteOperationCompleted);
            }
            this.InvokeAsync("ExportarArchivoByte", new object[] {
                        dataExportar}, this.ExportarArchivoByteOperationCompleted, userState);
        }
        
        private void OnExportarArchivoByteOperationCompleted(object arg) {
            if ((this.ExportarArchivoByteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportarArchivoByteCompleted(this, new ExportarArchivoByteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFEIArchivoLF/SubirArchivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultImportarArchivo SubirArchivo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DatosSubirArchivo dataImportar) {
            object[] results = this.Invoke("SubirArchivo", new object[] {
                        dataImportar});
            return ((ResultImportarArchivo)(results[0]));
        }
        
        /// <remarks/>
        public void SubirArchivoAsync(DatosSubirArchivo dataImportar) {
            this.SubirArchivoAsync(dataImportar, null);
        }
        
        /// <remarks/>
        public void SubirArchivoAsync(DatosSubirArchivo dataImportar, object userState) {
            if ((this.SubirArchivoOperationCompleted == null)) {
                this.SubirArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubirArchivoOperationCompleted);
            }
            this.InvokeAsync("SubirArchivo", new object[] {
                        dataImportar}, this.SubirArchivoOperationCompleted, userState);
        }
        
        private void OnSubirArchivoOperationCompleted(object arg) {
            if ((this.SubirArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubirArchivoCompleted(this, new SubirArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFEIArchivoLF/SubirArchivoMasivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.SoapLaserFiche")]
        public ResultImportarArchivo[] SubirArchivoMasivo([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.SoapLaserFiche")] DatosSubirArchivo[] lstDataImportar) {
            object[] results = this.Invoke("SubirArchivoMasivo", new object[] {
                        lstDataImportar});
            return ((ResultImportarArchivo[])(results[0]));
        }
        
        /// <remarks/>
        public void SubirArchivoMasivoAsync(DatosSubirArchivo[] lstDataImportar) {
            this.SubirArchivoMasivoAsync(lstDataImportar, null);
        }
        
        /// <remarks/>
        public void SubirArchivoMasivoAsync(DatosSubirArchivo[] lstDataImportar, object userState) {
            if ((this.SubirArchivoMasivoOperationCompleted == null)) {
                this.SubirArchivoMasivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubirArchivoMasivoOperationCompleted);
            }
            this.InvokeAsync("SubirArchivoMasivo", new object[] {
                        lstDataImportar}, this.SubirArchivoMasivoOperationCompleted, userState);
        }
        
        private void OnSubirArchivoMasivoOperationCompleted(object arg) {
            if ((this.SubirArchivoMasivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubirArchivoMasivoCompleted(this, new SubirArchivoMasivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.SoapLaserFiche")]
    public partial class DatosDescargarArchivo {
        
        private int idArchivoField;
        
        private bool idArchivoFieldSpecified;
        
        private string nombreArchivoField;
        
        private string nombreCarpetaField;
        
        /// <remarks/>
        public int IdArchivo {
            get {
                return this.idArchivoField;
            }
            set {
                this.idArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdArchivoSpecified {
            get {
                return this.idArchivoFieldSpecified;
            }
            set {
                this.idArchivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreCarpeta {
            get {
                return this.nombreCarpetaField;
            }
            set {
                this.nombreCarpetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.SoapLaserFiche")]
    public partial class ResultImportarArchivo {
        
        private int idEntradaLFField;
        
        private bool idEntradaLFFieldSpecified;
        
        private string mesageImportarField;
        
        private ResultExportarArchByte resultExportarArchByteField;
        
        private bool boolImportarField;
        
        private bool boolImportarFieldSpecified;
        
        /// <remarks/>
        public int IdEntradaLF {
            get {
                return this.idEntradaLFField;
            }
            set {
                this.idEntradaLFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdEntradaLFSpecified {
            get {
                return this.idEntradaLFFieldSpecified;
            }
            set {
                this.idEntradaLFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MesageImportar {
            get {
                return this.mesageImportarField;
            }
            set {
                this.mesageImportarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultExportarArchByte ResultExportarArchByte {
            get {
                return this.resultExportarArchByteField;
            }
            set {
                this.resultExportarArchByteField = value;
            }
        }
        
        /// <remarks/>
        public bool boolImportar {
            get {
                return this.boolImportarField;
            }
            set {
                this.boolImportarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boolImportarSpecified {
            get {
                return this.boolImportarFieldSpecified;
            }
            set {
                this.boolImportarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.SoapLaserFiche")]
    public partial class ResultExportarArchByte {
        
        private string extensionArchivoField;
        
        private string mesageExportarField;
        
        private string nombreArchivoField;
        
        private string nombreCarpetaField;
        
        private int numImagenesField;
        
        private bool numImagenesFieldSpecified;
        
        private string tipoContenidoMIMEField;
        
        private byte[] archivoField;
        
        private bool boolExportarField;
        
        private bool boolExportarFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExtensionArchivo {
            get {
                return this.extensionArchivoField;
            }
            set {
                this.extensionArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MesageExportar {
            get {
                return this.mesageExportarField;
            }
            set {
                this.mesageExportarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreCarpeta {
            get {
                return this.nombreCarpetaField;
            }
            set {
                this.nombreCarpetaField = value;
            }
        }
        
        /// <remarks/>
        public int NumImagenes {
            get {
                return this.numImagenesField;
            }
            set {
                this.numImagenesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumImagenesSpecified {
            get {
                return this.numImagenesFieldSpecified;
            }
            set {
                this.numImagenesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoContenidoMIME {
            get {
                return this.tipoContenidoMIMEField;
            }
            set {
                this.tipoContenidoMIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        public bool boolExportar {
            get {
                return this.boolExportarField;
            }
            set {
                this.boolExportarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boolExportarSpecified {
            get {
                return this.boolExportarFieldSpecified;
            }
            set {
                this.boolExportarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.SoapLaserFiche")]
    public partial class DatosSubirArchivo {
        
        private byte[] byteArchivoField;
        
        private string dirLocalDescargaArchivoField;
        
        private string extensionArchivoField;
        
        private string nombreCarpetaLFField;
        
        private string nombreComoSeGuardaArchivoLFField;
        
        private string nombreSubCarpetaLFField;
        
        private string nombreVolumenLFField;
        
        private string tipoContenidoMIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] ByteArchivo {
            get {
                return this.byteArchivoField;
            }
            set {
                this.byteArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DirLocalDescargaArchivo {
            get {
                return this.dirLocalDescargaArchivoField;
            }
            set {
                this.dirLocalDescargaArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExtensionArchivo {
            get {
                return this.extensionArchivoField;
            }
            set {
                this.extensionArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreCarpetaLF {
            get {
                return this.nombreCarpetaLFField;
            }
            set {
                this.nombreCarpetaLFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreComoSeGuardaArchivoLF {
            get {
                return this.nombreComoSeGuardaArchivoLFField;
            }
            set {
                this.nombreComoSeGuardaArchivoLFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreSubCarpetaLF {
            get {
                return this.nombreSubCarpetaLFField;
            }
            set {
                this.nombreSubCarpetaLFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreVolumenLF {
            get {
                return this.nombreVolumenLFField;
            }
            set {
                this.nombreVolumenLFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoContenidoMIME {
            get {
                return this.tipoContenidoMIMEField;
            }
            set {
                this.tipoContenidoMIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.SoapLaserFiche")]
    public partial class DatosExportarArchByte {
        
        private int idArchivoField;
        
        private bool idArchivoFieldSpecified;
        
        /// <remarks/>
        public int IdArchivo {
            get {
                return this.idArchivoField;
            }
            set {
                this.idArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdArchivoSpecified {
            get {
                return this.idArchivoFieldSpecified;
            }
            set {
                this.idArchivoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Mincetur.SG.OI.SoapLaserFiche")]
    public partial class ResultExportarArch {
        
        private string mesageExportarField;
        
        private bool boolExportarField;
        
        private bool boolExportarFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MesageExportar {
            get {
                return this.mesageExportarField;
            }
            set {
                this.mesageExportarField = value;
            }
        }
        
        /// <remarks/>
        public bool boolExportar {
            get {
                return this.boolExportarField;
            }
            set {
                this.boolExportarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boolExportarSpecified {
            get {
                return this.boolExportarFieldSpecified;
            }
            set {
                this.boolExportarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DescargarArchivoCompletedEventHandler(object sender, DescargarArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DescargarArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DescargarArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultExportarArch Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultExportarArch)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportarArchivoByteCompletedEventHandler(object sender, ExportarArchivoByteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportarArchivoByteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportarArchivoByteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultExportarArchByte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultExportarArchByte)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SubirArchivoCompletedEventHandler(object sender, SubirArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubirArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubirArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultImportarArchivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultImportarArchivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SubirArchivoMasivoCompletedEventHandler(object sender, SubirArchivoMasivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubirArchivoMasivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubirArchivoMasivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultImportarArchivo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultImportarArchivo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591