//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.soap.Servicio.Correo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWCFBorradorElectIntegracionEnviar", Namespace="http://tempuri.org/")]
    public partial class WCFBorradorElectIntegracionEnviar : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviarCorreoDocumentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFBorradorElectIntegracionEnviar() {
            this.Url = global::Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties.Settings.Default.Utilitarios_soap_Servicio_Correo_WCFBorradorElectIntegracionEnviar;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviarCorreoDocumentoCompletedEventHandler EnviarCorreoDocumentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFBorradorElectIntegracionEnviar/EnviarCorreoDocumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Resultado EnviarCorreoDocumento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FormatoMovi request) {
            object[] results = this.Invoke("EnviarCorreoDocumento", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarCorreoDocumentoAsync(FormatoMovi request) {
            this.EnviarCorreoDocumentoAsync(request, null);
        }
        
        /// <remarks/>
        public void EnviarCorreoDocumentoAsync(FormatoMovi request, object userState) {
            if ((this.EnviarCorreoDocumentoOperationCompleted == null)) {
                this.EnviarCorreoDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarCorreoDocumentoOperationCompleted);
            }
            this.InvokeAsync("EnviarCorreoDocumento", new object[] {
                        request}, this.EnviarCorreoDocumentoOperationCompleted, userState);
        }
        
        private void OnEnviarCorreoDocumentoOperationCompleted(object arg) {
            if ((this.EnviarCorreoDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarCorreoDocumentoCompleted(this, new EnviarCorreoDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Mincetur.Administracion.AplBorradorElectronico.ServicioIntegracionBorradorElect")]
    public partial class FormatoMovi {
        
        private int idDocField;
        
        private int idMoviAntField;
        
        private bool idMoviAntFieldSpecified;
        
        private Estorg estorgRemiteField;
        
        private Movi[] lstMoviField;
        
        private int idResponsableField;
        
        private bool idResponsableFieldSpecified;
        
        private int idUsuField;
        
        private bool idUsuFieldSpecified;
        
        private int idSisField;
        
        private bool idSisFieldSpecified;
        
        private string ipField;
        
        private string oprField;
        
        /// <remarks/>
        public int IdDoc {
            get {
                return this.idDocField;
            }
            set {
                this.idDocField = value;
            }
        }
        
        /// <remarks/>
        public int IdMoviAnt {
            get {
                return this.idMoviAntField;
            }
            set {
                this.idMoviAntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdMoviAntSpecified {
            get {
                return this.idMoviAntFieldSpecified;
            }
            set {
                this.idMoviAntFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Estorg EstorgRemite {
            get {
                return this.estorgRemiteField;
            }
            set {
                this.estorgRemiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Movi[] lstMovi {
            get {
                return this.lstMoviField;
            }
            set {
                this.lstMoviField = value;
            }
        }
        
        /// <remarks/>
        public int IdResponsable {
            get {
                return this.idResponsableField;
            }
            set {
                this.idResponsableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdResponsableSpecified {
            get {
                return this.idResponsableFieldSpecified;
            }
            set {
                this.idResponsableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdUsu {
            get {
                return this.idUsuField;
            }
            set {
                this.idUsuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUsuSpecified {
            get {
                return this.idUsuFieldSpecified;
            }
            set {
                this.idUsuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdSis {
            get {
                return this.idSisField;
            }
            set {
                this.idSisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSisSpecified {
            get {
                return this.idSisFieldSpecified;
            }
            set {
                this.idSisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Opr {
            get {
                return this.oprField;
            }
            set {
                this.oprField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Mincetur.Administracion.AplBorradorElectronico.ServicioIntegracionBorradorElect")]
    public partial class Estorg {
        
        private int idSubField;
        
        private bool idSubFieldSpecified;
        
        private string idSubofiField;
        
        /// <remarks/>
        public int IdSub {
            get {
                return this.idSubField;
            }
            set {
                this.idSubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSubSpecified {
            get {
                return this.idSubFieldSpecified;
            }
            set {
                this.idSubFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdSubofi {
            get {
                return this.idSubofiField;
            }
            set {
                this.idSubofiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Mincetur.Administracion.AplBorradorElectronico.ServicioIntegracionBorradorElect")]
    public partial class Resultado {
        
        private int idTipoField;
        
        private bool idTipoFieldSpecified;
        
        private string idErrorField;
        
        private string desErrorField;
        
        private string valorField;
        
        private string valor1Field;
        
        private string valor2Field;
        
        /// <remarks/>
        public int IdTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdTipoSpecified {
            get {
                return this.idTipoFieldSpecified;
            }
            set {
                this.idTipoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdError {
            get {
                return this.idErrorField;
            }
            set {
                this.idErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesError {
            get {
                return this.desErrorField;
            }
            set {
                this.desErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor1 {
            get {
                return this.valor1Field;
            }
            set {
                this.valor1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valor2 {
            get {
                return this.valor2Field;
            }
            set {
                this.valor2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Mincetur.Administracion.AplBorradorElectronico.ServicioIntegracionBorradorElect")]
    public partial class Movi {
        
        private int idAccionField;
        
        private bool idAccionFieldSpecified;
        
        private int idMoviField;
        
        private bool idMoviFieldSpecified;
        
        private int idAsignaField;
        
        private bool idAsignaFieldSpecified;
        
        private Estorg estorgField;
        
        private int idUsuFuncField;
        
        private bool idUsuFuncFieldSpecified;
        
        private string desObsField;
        
        private int flgOfiFunField;
        
        private bool flgOfiFunFieldSpecified;
        
        /// <remarks/>
        public int IdAccion {
            get {
                return this.idAccionField;
            }
            set {
                this.idAccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdAccionSpecified {
            get {
                return this.idAccionFieldSpecified;
            }
            set {
                this.idAccionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdMovi {
            get {
                return this.idMoviField;
            }
            set {
                this.idMoviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdMoviSpecified {
            get {
                return this.idMoviFieldSpecified;
            }
            set {
                this.idMoviFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdAsigna {
            get {
                return this.idAsignaField;
            }
            set {
                this.idAsignaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdAsignaSpecified {
            get {
                return this.idAsignaFieldSpecified;
            }
            set {
                this.idAsignaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Estorg Estorg {
            get {
                return this.estorgField;
            }
            set {
                this.estorgField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuFunc {
            get {
                return this.idUsuFuncField;
            }
            set {
                this.idUsuFuncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUsuFuncSpecified {
            get {
                return this.idUsuFuncFieldSpecified;
            }
            set {
                this.idUsuFuncFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DesObs {
            get {
                return this.desObsField;
            }
            set {
                this.desObsField = value;
            }
        }
        
        /// <remarks/>
        public int FlgOfiFun {
            get {
                return this.flgOfiFunField;
            }
            set {
                this.flgOfiFunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlgOfiFunSpecified {
            get {
                return this.flgOfiFunFieldSpecified;
            }
            set {
                this.flgOfiFunFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EnviarCorreoDocumentoCompletedEventHandler(object sender, EnviarCorreoDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarCorreoDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarCorreoDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591