//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mincetur.Administracion.AplTramiteVirtualPublico.Utilitarios.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioSeguridad/WCFSeguridadEncripDesencrip.svc" +
            "")]
        public string Utilitarios_servicioSeguridad_WCFSeguridadEncripDesencrip_WCFSeguridadEncripDesencrip {
            get {
                return ((string)(this["Utilitarios_servicioSeguridad_WCFSeguridadEncripDesencrip_WCFSeguridadEncripDesen" +
                    "crip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/SoapLaserfiche/WCFEIArchivoLF.svc")]
        public string Utilitarios_soap_ServicioArchivoLaserfiche_WCFEIArchivoLF {
            get {
                return ((string)(this["Utilitarios_soap_ServicioArchivoLaserfiche_WCFEIArchivoLF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGeneralUtil/WCFGeneralesEstorg.svc")]
        public string Utilitarios_soap_ServicioGeneralUtil_Estorg_WCFGeneralesEstorg {
            get {
                return ((string)(this["Utilitarios_soap_ServicioGeneralUtil_Estorg_WCFGeneralesEstorg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioSeguridad/WCFSeguridadSistema.svc")]
        public string Utilitarios_soap_ServicioSeguridad_SeguridadSistema_WCFSeguridadSistema {
            get {
                return ((string)(this["Utilitarios_soap_ServicioSeguridad_SeguridadSistema_WCFSeguridadSistema"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/wsSunat/sistema/ws/wsContribuyente.asmx")]
        public string Utilitarios_ServicioSunatContribuyente_wsContribuyente {
            get {
                return ((string)(this["Utilitarios_ServicioSunatContribuyente_wsContribuyente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGeneralUtil/WCFGeneralesTipoDocu.svc")]
        public string Utilitarios_servicioGeneralesTipoDocu_WCFGeneralesTipoDocu {
            get {
                return ((string)(this["Utilitarios_servicioGeneralesTipoDocu_WCFGeneralesTipoDocu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGeneralUtil/WCFGeneralesTipoTele.svc")]
        public string Utilitarios_servicioGeneralesTipoTele_WCFGeneralesTipoTele {
            get {
                return ((string)(this["Utilitarios_servicioGeneralesTipoTele_WCFGeneralesTipoTele"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGeneralUtil/WCFGeneralesUbigeo.svc")]
        public string Utilitarios_servicioGeneralesUbigeo_WCFGeneralesUbigeo {
            get {
                return ((string)(this["Utilitarios_servicioGeneralesUbigeo_WCFGeneralesUbigeo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGeneralUtil/WCFGeneralesVia.svc")]
        public string Utilitarios_servicioGeneralesVia_WCFGeneralesVia {
            get {
                return ((string)(this["Utilitarios_servicioGeneralesVia_WCFGeneralesVia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGeneralUtil/WCFGeneralesZona.svc")]
        public string Utilitarios_servicioGeneralesZona_WCFGeneralesZona {
            get {
                return ((string)(this["Utilitarios_servicioGeneralesZona_WCFGeneralesZona"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGeneralUtil/WCFGeneralesDocIdentidad.svc")]
        public string Utilitarios_servicioDocumento_WCFGeneralDocIdentidad {
            get {
                return ((string)(this["Utilitarios_servicioDocumento_WCFGeneralDocIdentidad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioIntegracion/DirectorioPersonaPide/soap/WC" +
            "FIntegracionPide.svc")]
        public string Utilitarios_servicioPide_WCFIntegracionPide {
            get {
                return ((string)(this["Utilitarios_servicioPide_WCFIntegracionPide"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGeneralUtil/WCFGeneralesCorreo.svc")]
        public string Utilitarios_soap_ServicioGeneralUtil_Correo_WCFGeneralesCorreo {
            get {
                return ((string)(this["Utilitarios_soap_ServicioGeneralUtil_Correo_WCFGeneralesCorreo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/ServicioBorradorDig/Integracion/Services/WCFBorra" +
            "dorElectIntegracionEnviar.svc")]
        public string Utilitarios_soap_Servicio_Correo_WCFBorradorElectIntegracionEnviar {
            get {
                return ((string)(this["Utilitarios_soap_Servicio_Correo_WCFBorradorElectIntegracionEnviar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioSeguridad/WCFSeguridadLog.svc")]
        public string Utilitarios_soap_servicioGestorSeguridadLogError_WCFSeguridadLog {
            get {
                return ((string)(this["Utilitarios_soap_servicioGestorSeguridadLogError_WCFSeguridadLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioGenerales/docCms/Services/WCFGeneralesDoc" +
            "CmsConsulta.svc")]
        public string Utilitarios_servicioGenerales_DocCmsConsulta_WCFGeneralesDocCmsConsulta {
            get {
                return ((string)(this["Utilitarios_servicioGenerales_DocCmsConsulta_WCFGeneralesDocCmsConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioFileServer/WCFgestorFileServer.svc")]
        public string Utilitarios_servicioGestorFileServer_WCFgestorFileServer {
            get {
                return ((string)(this["Utilitarios_servicioGestorFileServer_WCFgestorFileServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.mincetur.gob.pe:8010/servicioSeguridad/services/WCFSeguridadUsuSisRolE" +
            "ntEstorg.svc")]
        public string Utilitarios_soap_ServicioUsuSisRolEntEstorg_WCFSeguridadUsuSisRolEntEstorg {
            get {
                return ((string)(this["Utilitarios_soap_ServicioUsuSisRolEntEstorg_WCFSeguridadUsuSisRolEntEstorg"]));
            }
        }
    }
}
